        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Tarefas do Projeto - <?php echo utf8_decode($projeto->projeto_nome); ?></h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Nova Tarefa de <?php echo utf8_decode($projeto->projeto_nome);?> <small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                       <li><a class="link"  href="<?php echo $this->url('tarefa_projeto/consulta', array('id' => $projeto->projeto_id)); ?>" ><i class="fa fa-chevron-left" aria-hidden="true"></i> Voltar</a></li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content">


                  <!-- Smart Wizard -->
                  <p>Esse &eacute; o formul&aacute;rio onde deve ser preenchidas todas as informa&ccedil;es da nova tarefa.</p>
                  
  				<form method="post" action="<?php echo $this->url('tarefa_projeto/add', array('id' => $id));?>" role="form" class="form-horizontal form-label-left">
              
                  <div>                    
                                                
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="tarefa_nome">T&iacute;tulo <span class="required">*</span>
                          </label>
                          <div class="col-md-5 col-sm-6 col-xs-12">
                            <input type="text" id="tarefa_nome" name="tarefa_nome" required="required" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>                                        
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="usuario_id">Respons&aacute;vel <span class="required">*</span>
                          </label>
                          <div class="col-md-4 col-sm-4 col-xs-12">
                          	<select name="usuario_id" id="usuario_id"  required="required"  class="form-control col-md-7 col-xs-12">
                          	<?php 
                          			foreach($usuarios as $usuario){
                          	?>
                          	
                          		<option value="<?php echo $usuario->usuario_id; ?>"><?php echo utf8_decode($usuario->usuario_nome); ?></option>
                          	<?php 
                          			}
                          	?>
                          	</select>
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="tarefa_descricao">Descri&ccedil;&atilde;o<span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea id="tarefa_descricao" name="tarefa_descricao" required="required" class="form-control col-md-7 col-xs-12"></textarea>
                          </div>
                        </div>	
                                                
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="tarefa_status">Status <span class="required">*</span>
                          </label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                          	<select name="tarefa_status" id="tarefa_status"  required="required"  class="form-control col-md-7 col-xs-12">
                          		<option value="Aberta">Aberta</option>
                          		<option value="Em Andamento">Em andamento</option>
                          		<option value="Suspensa">Suspensa</option>
                          		<option value="Encerrada">Encerrada</option>
                          	</select>
                          </div>
                        </div>	
                        
                        <div class="form-group">
                          <label for="tarefa_data_inicio" class="control-label col-md-3 col-sm-3 col-xs-12">Data de in&iacute;cio <span class="required">*</span></label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                            <input id="tarefa_data_inicio" class="form-control col-md-7 col-xs-12" type="date" name="tarefa_data_inicio">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label for="tarefa_data_previsao_termino" class="control-label col-md-3 col-sm-3 col-xs-12">Previs&atilde;o de T&eacute;rmino <span class="required">*</span> </label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                            <input id="tarefa_data_previsao_termino" class="form-control col-md-7 col-xs-12" type="date" name="tarefa_data_previsao_termino">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label for="tarefa_data_termino" class="control-label col-md-3 col-sm-3 col-xs-12">Data real de t&eacute;rmino</label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                            <input id="tarefa_data_termino" class="form-control col-md-7 col-xs-12" type="date" name="tarefa_data_termino">
                          </div>
                        </div>		  
					  
                        <div class="form-group"> 
                          	<label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                        
						    <div class="control-label col-sm-1">
						      <button type="submit" class="btn btn-default">Cadastrar</button>
						    </div>
						    <div class="control-label col-sm-2">
						       <button type="reset" class="btn btn-default" onclick="location.href='<?php echo $this->url('tarefa_projeto/consulta', array('action'=>'consulta', 'id' => $id));?>'">Cancelar</button>
						     </div>
					  </div>
					  
                  </div>
                  </form>
                  <!-- End SmartWizard Content -->

                </div>
              </div>
            </div>

          </div>
        </div>