<?php

 $title = 'Excluir Tarefa';
 $this->headTitle($title);
 ?>

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Tarefas do Projeto - <?php echo utf8_decode($projeto->projeto_nome); ?></h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12" style="text-align: center;">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Excluir Tarefa de <?php echo utf8_decode($projeto->projeto_nome); ?><small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="link"  href="<?php echo $this->url('tarefa_projeto/consulta', array('id' => $projeto->projeto_id)); ?>" ><i class="fa fa-chevron-left" aria-hidden="true"></i> Voltar</a></li>
                     <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>                      
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content"> 
 
				 <p>Tem certeza que deseja excluir a tarefa <br>
				     <strong><?php echo '"'.utf8_decode($tarefa->tarefa_nome).'"'; ?></strong> do projeto ?
				 </p>
 
                  
  				<form action="<?php echo $this->url('tarefa_projeto/delete', array('action' => 'delete','projeto_id'=>$projeto_id, 'id' => $this->id)); ?>" method="post" role="form" class="form-horizontal form-label-left">
              
                  <div  style="text-align: center;">
                  
                                            
     
     						<input type="hidden" name="id" value="<?php echo (int) $tarefa->tarefa_id; ?>" />
     								
							  <div class="form-group"> 
							    <div class="control-label col-md-6 col-sm-6 col-xs-6">
							      <button type="submit" class="btn btn-default" name="submit" value="Sim">Sim</button>
							    </div>
							    <div class="control-label col-md-1 col-sm-1 col-xs-1"">
							      <button type="submit" class="btn btn-default" name="submit" value="Nao">N&atilde;o</button>
							    </div>
							  </div>
					  
                  </div>
                  </form>
                  <!-- End SmartWizard Content -->

                </div>
              </div>
            </div>

          </div>
        </div>