<?php

 $title = 'Visualizar Tarefa do Projeto';
 $this->headTitle($title);
 ?>
 
        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Tarefas do Projeto - <?php echo utf8_decode($projeto->projeto_nome); ?></h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12" style="text-align: center;">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2><?php echo $title;?> <?php echo utf8_decode($projeto->projeto_nome); ?><small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="link"  href="<?php echo $this->url('tarefa_projeto/consulta', array('id' => $projeto->projeto_id)); ?>" ><i class="fa fa-chevron-left" aria-hidden="true"></i> Voltar</a></li>
                  	<li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>                      
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content"> 
 
                  <!-- Smart Wizard --> 
                  
  				<form action="" method="post" role="form" class="form-horizontal form-label-left">
  				
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome">T&iacute;tulo:
                          </label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">
                          <label class="control-label "><?php echo utf8_decode($tarefa->tarefa_nome); ?>
                          </label>      	
                          </div>
                        </div>	
                        <?php 

                          $array_usuarios = Array();
                          
                          foreach($usuarios as $usuario){
                          	$array_usuarios[$usuario->usuario_id] = utf8_decode($usuario->usuario_nome);
                          }
                                                    
                          ?>
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome">Respons&aacute;vel:
                          </label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">
                          <label class="control-label "><?php echo $array_usuarios[$tarefa->usuario_id];?>
                          </label>      	
                          </div>
                        </div>		
                        	
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome">Descri&ccedil;&atilde;o: </label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">                          
                          	<label class="control-label"><?php echo utf8_decode(trim($tarefa->tarefa_descricao)); ?></label>  
                          </div>
                        </div>	
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome">Status:</label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">
                          	<label class="control-label"><?php echo $tarefa->tarefa_status; ?></label>      	
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome">Data In&iacute;cio:</label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">
                          	<label class="control-label"><?php echo date('d/m/Y', strtotime($tarefa->tarefa_data_inicio)); ?></label>      	
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome">Previs&atilde;o de T&eacute;rmino:</label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">
                          	<label class="control-label"><?php echo date('d/m/Y', strtotime($tarefa->tarefa_data_previsao_termino)); ?></label>      	
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome">Data T&eacute;rmino:</label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">
                          	<label class="control-label"><?php echo date('d/m/Y', strtotime($tarefa->tarefa_data_termino)); ?></label>      	
                          </div>
                        </div>
                  
                  </form>
                  <!-- End SmartWizard Content -->

                </div>
              </div>
            </div>

          </div>
        </div>