<?php 
     use Zend\Session\Container;  
	 $session_dados = new Container('usuario_dados');   
 ?> 
        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Acompanhamentos do Projeto - <?php echo utf8_decode($projeto->projeto_nome); ?></h3>
            </div>            
          </div>
          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Consultar Acompanhamentos de <?php echo  utf8_decode($projeto->projeto_nome);?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                   <li><a class="link"  href="<?php echo $this->url('projeto', array('id' => $projeto->projeto_id)); ?>" ><i class="fa fa-chevron-left" aria-hidden="true"></i> Voltar</a></li>
                   
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content" class="table-responsive">

                  <p>Lista todos os acompanhamentos do projeto</p>

                  <!-- start project list -->
                  <table  id="minhatabela" class="table table-striped">
                    <thead>
                      <tr>
                        <th style="width: 20%">Semana</th>
                        <th style="width: 20%">Data In&iacute;cio</th>
                        <th style="width: 20%">Data T&eacute;rmino</th>
                        <th style="width: 20%">Edi&ccedil;&atilde;o</th>
                      </tr>
                    </thead>
                    
                    <tbody>
                    <?php 
                 
                    if($validaAcompanhamento == 'sim'){
                    ?>
                    <div class="alert alert-danger" id="alerta" name="alerta" >
						  <strong>Projeto de Alto Risco com Pend&ecirc;ncia de Acompanhamento!</strong> 
					</div>
						
                    <?php
                    }
                    foreach ($acompanhamentosProjeto as $acompanhamento)
                    {
                    	if(is_object($acompanhamento)){
                    ?>
                      <tr>
                        <td><?php echo $acompanhamento->projeto_semana; ?></td>
                        <td><?php echo date('d/m/Y', strtotime($acompanhamento->projeto_semana_data_inicio)); ?></td>
                        <td><?php echo date('d/m/Y', strtotime($acompanhamento->projeto_semana_data_fim)); ?></td>
                        <td>
		              <?php if(in_array('acompanhamento_projeto/detalhe', $session_dados->funcionalidades_usuario)){ ?>
                          <a href="<?php echo $this->url('acompanhamento_projeto/detalhe', array('id' => $acompanhamento->projeto_semana_id, 'projeto_id' => $id)); ?>" data-toggle="tooltip" data-placement="top" title="Ver Detalhado" class="btn btn-info btn-xs"><i class="fa fa-folder"></i>  </a>
                      <?php }?>
                         <?php if(in_array('acompanhamento_projeto/edit', $session_dados->funcionalidades_usuario)){ ?>
                         <a href="<?php echo $this->url('acompanhamento_projeto/edit', array('id' => $acompanhamento->projeto_semana_id, 'projeto_id' => $id)); ?>" data-toggle="tooltip" data-placement="top" title="Realizar Acompanhamento" class="btn btn-warning btn-xs"><i class="fa fa-calendar-o"></i>  </a>
                      <?php }?>
                        </td>
                      </tr>
                      <?php 
							
						}
                    }
                      ?>                      
                    </tbody>
                  </table>
                  <!-- end project list -->

                </div>
              </div>
            </div>
          </div>
        </div>

  <script src="<?php echo $this->basePath('js/bootstrap.min.js'); ?>"></script>

  <!-- chart js -->
  <script src="<?php echo $this->basePath('js/chartjs/chart.min.js'); ?>"></script>
  <!-- bootstrap progress js -->
  <script src="<?php echo $this->basePath('js/progressbar/bootstrap-progressbar.min.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/nicescroll/jquery.nicescroll.min.js'); ?>"></script>
  <!-- icheck -->
  <script src="<?php echo $this->basePath('js/icheck/icheck.min.js'); ?>"></script>

  <script src="<?php echo $this->basePath('js/custom.js'); ?>"></script>

  <!-- pace -->
  <script src="<?php echo $this->basePath('js/pace/pace.min.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/jquery.dataTables.min.js'); ?>"></script>


		    <script>
			    $(document).ready(function(){
			        $('#minhatabela').dataTable();
			    });
		        
		    </script>
