<?php

 $title = 'Visualizar Acompanhamento do Projeto';
 $this->headTitle($title);
 ?>
 
        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Acompanhamentos do Projeto - <?php echo utf8_decode($projeto->projeto_nome); ?></h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12" style="text-align: center;">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2><?php echo $title;?> <?php echo utf8_decode($projeto->projeto_nome); ?><small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                      <li><a class="link"  href="<?php echo $this->url('acompanhamento_projeto/consulta', array('id' => $projeto->projeto_id)); ?>" ><i class="fa fa-chevron-left" aria-hidden="true"></i> Voltar</a></li>
                 	<li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>                      
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content"> 
 
                  <!-- Smart Wizard --> 
                  
  				<form action="" method="post" role="form" class="form-horizontal form-label-left">
  				
  						<div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_acompanhamento_semana">Semana:
                          </label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">
                           <label class="control-label "><?php echo $projetoSemana->projeto_semana; ?>
                          </label>      	
                          </div>
                        </div>		
                        	
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_acompanhamento_data_inicio">Data de In&iacute;cio: </label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">     
                            <label class="control-label"><?php echo date('d/m/Y', strtotime($projetoSemana->projeto_semana_data_inicio)); ?></label>  
                          </div>
                        </div>		
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_acompanhamento_data_termino">Data de T&eacute;rmino: </label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">                          
                            <label class="control-label"><?php echo date('d/m/Y', strtotime($projetoSemana->projeto_semana_data_fim)); ?></label>  
                          </div>
                        </div>	
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome">Descri&ccedil;&atilde;o: </label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">                          
                          	<label class="control-label"><?php if(isset($acompanhamento->projeto_semana_justificativa)){ echo trim(utf8_decode($acompanhamento->projeto_semana_justificativa));} ?></label>  
                          </div>
                        </div>		
                        
                  
                  </form>
                  <!-- End SmartWizard Content -->

                </div>
              </div>
            </div>

          </div>
        </div>              
 
