        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Acompanhamentos do Projeto - <?php echo utf8_decode($projeto->projeto_nome); ?></h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Editar Acompanhamento de <?php echo utf8_decode($projeto->projeto_nome);?> <small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="link"  href="<?php echo $this->url('acompanhamento_projeto/consulta', array('id' => $projeto->projeto_id)); ?>" ><i class="fa fa-chevron-left" aria-hidden="true"></i> Voltar</a></li>
                   </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content">

                  <!-- Smart Wizard -->
                  <p>Esse &eacute; o formul&aacute;rio onde deve ser preenchidas todas as informa&ccedil;&otilde;es do acompanhamento do projeto.</p>
                  
  				<form method="post" action="<?php echo $this->url('acompanhamento_projeto/edit', array('id' => $acompanhamento->projeto_semana_id, 'projeto_id' => $projeto_id));?>" role="form" class="form-horizontal form-label-left">
              
                  <div>                    
                        <input type="hidden" id="projeto_semana_justificativa_id" name="projeto_semana_justificativa_id" value="<?php echo $acompanhamento->projeto_semana_justificativa_id;?>">
                        <input type="hidden" id="projeto_semana_id" name="projeto_semana_id" value="<?php echo $acompanhamento->projeto_semana_id;?>">
                                       
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_acompanhamento_semana">Semana:
                          </label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">
                           <label class="control-label "><?php echo $projeto_semana->projeto_semana; ?>
                          </label>      	
                          </div>
                        </div>		
                        	
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_acompanhamento_data_inicio">Data de In&iacute;cio: </label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">     
                            <label class="control-label"><?php echo date('d/m/Y', strtotime($projeto_semana->projeto_semana_data_inicio)); ?></label>  
                          </div>
                        </div>		
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_acompanhamento_data_termino">Data de T&eacute;rmino: </label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">                          
                            <label class="control-label"><?php echo date('d/m/Y', strtotime($projeto_semana->projeto_semana_data_fim)); ?></label>  
                          </div>
                        </div>	
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_semana_justificativa">Descri&ccedil;&atilde;o<span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea id="projeto_semana_justificativa" name="projeto_semana_justificativa" required="required" class="form-control col-md-7 col-xs-12"> <?php echo trim($acompanhamento->projeto_semana_justificativa); ?></textarea>
                          </div>
                        </div>
					  
                        <div class="form-group"> 
                          	<label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                        
						    <div class="control-label col-sm-1">
						      <button type="submit" class="btn btn-default">Alterar</button>
						    </div>
						    <div class="control-label col-sm-2">
						       <button type="reset" class="btn btn-default" onclick="location.href='<?php echo $this->url('acompanhamento_projeto/consulta', array('action'=>'consulta', 'id' => $projeto_id));?>'">Cancelar</button>
						     </div>
					  </div>
					  
                  </div>
                  </form>
                  <!-- End SmartWizard Content -->

                </div>
              </div>
            </div>

          </div>
        </div>
