      <!-- page content -->
      <div class="right_col" role="main">

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Editar Acompanhamento</h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Editar Acompanhamento de <?php echo $projeto->projeto_nome;?> <small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content">

                  <!-- Smart Wizard -->
                  <p>Esse é o formulário onde deve ser preenchidas todas as informações do acompanhamento do projeto.</p>
                  
  				<form method="post" action="<?php echo $this->url('acompanhamento_projeto/edit', array('id' => $id, 'projeto_id' => $projeto_id));?>" role="form" class="form-horizontal form-label-left">
              
                  <div>                    
                        <input type="hidden" id="projeto_acompanhamento_semana" name="projeto_acompanhamento_semana" value="<?php echo $acompanhamento->projeto_acompanhamento_semana;?>">
                        <input type="hidden" id="projeto_acompanhamento_data_inicio" name="projeto_acompanhamento_data_inicio" value="<?php echo $acompanhamento->projeto_acompanhamento_data_inicio;?>">
                        <input type="hidden" id="projeto_acompanhamento_data_termino" name="projeto_acompanhamento_data_termino" value="<?php echo $acompanhamento->projeto_acompanhamento_data_termino;?>">
                                       
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_acompanhamento_semana">Semana:
                          </label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">
                           <label class="control-label "><?php echo $acompanhamento->projeto_acompanhamento_semana; ?>
                          </label>      	
                          </div>
                        </div>		
                        	
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_acompanhamento_data_inicio">Data de Início: </label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">     
                            <label class="control-label"><?php echo date('d/m/Y', strtotime($acompanhamento->projeto_acompanhamento_data_inicio)); ?></label>  
                          </div>
                        </div>		
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_acompanhamento_data_termino">Data de Término: </label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">                          
                            <label class="control-label"><?php echo date('d/m/Y', strtotime($acompanhamento->projeto_acompanhamento_data_termino)); ?></label>  
                          </div>
                        </div>	
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_acompanhamento_descricao">Descrição<span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea id="projeto_acompanhamento_descricao" name="projeto_acompanhamento_descricao" required="required" class="form-control col-md-7 col-xs-12"> <?php echo trim($acompanhamento->projeto_acompanhamento_descricao); ?></textarea>
                          </div>
                        </div>
					  
                        <div class="form-group"> 
                          	<label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                        
						    <div class="control-label col-sm-1">
						      <button type="submit" class="btn btn-default">Alterar</button>
						    </div>
						    <div class="control-label col-sm-2">
						       <button type="reset" class="btn btn-default" onclick="location.href='<?php echo $this->url('acompanhamento_projeto/consulta', array('action'=>'consulta', 'id' => $projeto_id));?>'">Cancelar</button>
						     </div>
					  </div>
					  
                  </div>
                  </form>
                  <!-- End SmartWizard Content -->

                </div>
              </div>
            </div>

          </div>
        </div>

        <!-- footer content -->
        <footer>
          <div class="copyright-info">
            <p class="pull-right">© 2016 Produzido por Laislla Costa Ramos
            </p>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
      <!-- /page content -->
