      <!-- page content -->
      <div class="right_col" role="main">

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Projeto</h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Novo Projeto <small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"></a>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>                      
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content">


                  <!-- Smart Wizard -->
                  <p>Esse é o formulário onde deve ser preenchidas todas as informações do novo projeto.</p>
                  
  				<form method="post" action="<?php echo $this->url('projeto/add',  array('action'=>'add'));?>" role="form" class="form-horizontal form-label-left">
              
                  <div>
              
                   
                    <div>

                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_nome">Título <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" id="projeto_nome" name="projeto_nome" required="required" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_gerente_id">Gerente Responsável <span class="required">*</span>
                          </label>
                          <div class="col-md-4 col-sm-4 col-xs-12">
                          	<select name="projeto_gerente_id" id="projeto_gerente_id"  required="required"  class="form-control col-md-7 col-xs-12">
                          	<?php 
                          			foreach($usuarios as $usuario){
                          	?>
                          	
                          		<option value="<?php echo $usuario->usuario_id; ?>"><?php echo $usuario->usuario_nome?></option>
                          	<?php 
                          			}
                          	?>
                          	</select>
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label for="projeto_data_inicio" class="control-label col-md-3 col-sm-3 col-xs-12">Data de início <span class="required">*</span></label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                            <input id="projeto_data_inicio" class="form-control col-md-7 col-xs-12" type="date" name="projeto_data_inicio">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label for="projeto_data_previsao_termino" class="control-label col-md-3 col-sm-3 col-xs-12">Previsão de Término <span class="required">*</span> </label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                            <input id="projeto_data_previsao_termino" class="form-control col-md-7 col-xs-12" type="date" name="projeto_data_previsao_termino">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label for="projeto_data_real_termino" class="control-label col-md-3 col-sm-3 col-xs-12">Data real de término</label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                            <input id="projeto_data_real_termino" class="form-control col-md-7 col-xs-12" type="date" name="projeto_data_real_termino">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_orcamento_total">Orçamento Total<span class="required">*</span>
                          </label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                            <input type="text" id="projeto_orcamento_total" name="projeto_orcamento_total" required="required" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_descricao">Descrição<span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea id="projeto_descricao" name="projeto_descricao" required="required" class="form-control col-md-7 col-xs-12"></textarea>
                          </div>
                        </div>
                     
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="riscoRadios">Classificação de Risco<span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <div class="radio">
	                          <label>
	                            <input type="radio" value="Baixo risco" id="Baixo risco" name="riscoRadios"> Baixo risco
	                          </label>
	                        </div>
	                        <div class="radio">
	                          <label>
	                            <input type="radio" value="Medio risco" id="Medio risco" name="riscoRadios"> Médio risco
	                          </label>
	                        </div>
	                        <div class="radio">
	                          <label>
	                            <input type="radio" value="Alto risco" id="Alto risco" name="riscoRadios"> Alto risco
	                          </label>
	                        </div>
                            
                          </div>
                        </div>                 
                    
                        <div class="form-group"> 
                          	<label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                        
						    <div class="control-label col-sm-1">
						      <button type="submit" class="btn btn-default">Cadastrar</button>
						    </div>
						    <div class="control-label col-sm-2">
						      <button type="reset" class="btn btn-default" onclick="location.href='<?php echo $this->url('projeto', array('action'=>'index'));?>'">Cancelar</button>
						    </div>
					  </div>
					  
                  </div>
                  </form>
                  <!-- End SmartWizard Content -->

                </div>
              </div>
            </div>

          </div>
        </div>

        <!-- footer content -->
        <footer>
          <div class="copyright-info">
            <p class="pull-right">© 2016 Produzido por Laislla Costa Ramos
            </p>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
      <!-- /page content -->
