
      <!-- page content -->
      <div class="right_col" role="main">

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Projeto Detalhes </h3>
            </div>

            <div class="title_right">
              <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search for...">
                  <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Buscar!</button>
                        </span>
                </div>
              </div>
            </div>
          </div>
          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><?php echo $projeto->projeto_nome;?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li class="dropdown">
                      <a href="<?php echo $this->url('projeto/edit', array('id' => $projeto->projeto_id)); ?>" ><i class="fa fa-wrench"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>

                <div class="x_content">

                  <div class="col-md-9 col-sm-9 col-xs-12">

                    <ul class="stats-overview">
                      <li>
                        <span class="name"> Data Inicio </span>
                        <?php 		
								$projeto_data_inicio = explode('-', $projeto->projeto_data_inicio);
								$projeto_data_previsao_termino = explode('-', $projeto->projeto_data_previsao_termino);
								$projeto_data_real_termino = explode('-', $projeto->projeto_data_real_termino);
						?>
                        <span class="value text-success"> <?php echo $projeto_data_inicio[2]."/".$projeto_data_inicio[1]."/".$projeto_data_inicio[0]; ?> </span>
                      </li>
                      <li>
                        <span class="name"> Data Previsao Termino </span>
                        <span class="value text-success"> <?php echo $projeto_data_previsao_termino[2]."/".$projeto_data_previsao_termino[1]."/".$projeto_data_previsao_termino[0]; ?> </span>
                      </li>
                      <li class="hidden-phone">
                        <span class="name"> Data Termino </span>
                        <span class="value text-success"> <?php echo $projeto_data_real_termino[2]."/".$projeto_data_real_termino[1]."/".$projeto_data_real_termino[0]; ?> </span>
                      </li>
                    </ul>
                    <br />

                    <div id="mainb" style="height:350px;"></div>
                  </div>

                  <!-- start project-detail sidebar -->
                  <div class="col-md-3 col-sm-3 col-xs-12">

                    <section class="panel">

                      <div class="x_title">
                        <h2>Projeto Descricao</h2>
                        <div class="clearfix"></div>
                      </div>
                      <div class="panel-body">

                        <p><?php echo $projeto->projeto_descricao;?></p>
                        <br />

                        <div class="project_detail">

                          <p class="title">Gerente Responsavel</p>
                          <?php 

                          $array_usuarios = Array();
                          
                          foreach($usuarios as $usuario){
                          	$array_usuarios[$usuario->usuario_id] = $usuario->usuario_nome;
                          }
                                                    
                          ?>
                          <p><?php echo $array_usuarios[$projeto->projeto_gerente_id];?></p>
                          <p class="title">Orcamento Total</p>
                          <p><?php echo $projeto->projeto_orcamento_total;?></p>
                          <p class="title">Risco</p>
                          <p><?php echo $projeto->projeto_risco;?></p>
                          <p class="title">Status</p>
                          <p><?php echo $projeto->projeto_status;?></p>
                        </div>

                        <br />

                        <div class="text-center mtop20">
                          <a href="<?php echo $this->url('projeto/edit', array('id' => $projeto->projeto_id)); ?>"   class="btn btn-sm btn-primary">Alterar Projeto</a>
                          <a href="<?php echo $this->url('projeto/status', array('id' => $projeto->projeto_id)); ?>"   class="btn btn-sm btn-warning">Mudar Status</a>
                        </div>
                      </div>

                    </section>

                  </div>
                  <!-- end project-detail sidebar -->
                  
                  <div class="col-md-12 col-sm-12 col-xs-12">
	
	                      <h4>Membros do Projeto</h4>
							<div class="row">
				            <div class="col-md-12">
				              <div class="x_panel">
				                <div class="x_content">
				
				                  <div class="row">
				
				<?php 
				foreach ($membrosProjeto as $membro){
					
				?>
				                    <div class="col-md-4 col-sm-4 col-xs-12 animated fadeInDown">
				                      <div class="well profile_view">
				                        <div class="col-sm-12">
				                          <h4 class="brief"><i><?php echo $membro->projeto_membro_papel; ?></i></h4>
				                          <div class="left col-xs-7">
				                            <h2><?php echo $array_usuarios[$membro->usuario_id]; ?></h2>
				                          </div>
				                          <div class="right col-xs-5 text-center">
				                            <img src="<?php echo $this->basePath('images/img.jpg'); ?>" alt="" class="img-circle img-responsive">
				                          </div>
				                        </div>
				                        <div class="col-xs-12 bottom text-center">
				                          <div class="col-xs-12 col-sm-12 emphasis">
				                            <a  href="<?php echo $this->url('usuario/detalhe', array('id' => $membro->usuario_id)); ?>"  type="button" class="btn btn-primary btn-xs"> <i class="fa fa-user">
				                                                            </i> Ver Usuario</a>
				                          </div>
				                        </div>
				                      </div>
				                    </div>
				<?php 
				}
				?>
				                    
				                  </div>
				
				                </div>
				              </div>
				            </div>
				          </div>
	
	                    </div>

                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- footer content -->
        <footer>
          <div class="copyright-info">
            <p class="pull-right">© 2016 Produzido por Laislla Costa Ramos
            </p>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
      <!-- /page content -->
      

  <script src="<?php echo $this->basePath('js/bootstrap.min.js'); ?>"></script>
  
  <!-- chart js -->
  <script src="<?php echo $this->basePath('js/chartjs/chart.min.js'); ?>"></script>
  <!-- bootstrap progress js -->
  <script src="<?php echo $this->basePath('js/progressbar/bootstrap-progressbar.min.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/nicescroll/jquery.nicescroll.min.js'); ?>"></script>
  <!-- icheck -->
  <script src="<?php echo $this->basePath('js/icheck/icheck.min.js'); ?>"></script>

  <script src="<?php echo $this->basePath('js/custom.js'); ?>"></script>

  <!-- pace -->
  <script src="<?php echo $this->basePath('js/echart/echarts-all.js'); ?>"></script>
  <!-- pace -->
  <script src="<?php echo $this->basePath('js/echart/green.js'); ?>"></script>
  
  <!-- pace -->
  <script src="<?php echo $this->basePath('js/pace/pace.min.js'); ?>"></script>
  
  <script>
    var myChart9 = echarts.init(document.getElementById('mainb'), theme);
    myChart9.setOption({
      title: {
        x: 'center',
        y: 'top',
        padding: [0, 0, 20, 0],
        text: 'Tarefas por fase do Projeto',
        textStyle: {
          fontSize: 15,
          fontWeight: 'normal'
        }
      },
      tooltip: {
        trigger: 'axis'
      },
      toolbox: {
        show: true,
        feature: {
          dataView: {
            show: true,
            readOnly: false
          },
          restore: {
            show: true
          },
          saveAsImage: {
            show: true
          }
        }
      },
      calculable: true,
      legend: {
        data: ['Revenue', 'Cash Input', 'Time Spent'],
        y: 'bottom'
      },
      xAxis: [{
        type: 'category',
        data: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
      }],
      yAxis: [{
        type: 'value',
        name: 'Amount',
        axisLabel: {
          formatter: '{value} ml'
        }
      }, {
        type: 'value',
        name: 'Hours',
        axisLabel: {
          formatter: '{value} °C'
        }
      }],
      series: [{
        name: 'Revenue',
        type: 'bar',
        data: [2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3]
      }, {
        name: 'Cash Input',
        type: 'bar',
        data: [2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3]
      }, {
        name: 'Time Spent',
        type: 'line',
        yAxisIndex: 1,
        data: [2.0, 2.2, 3.3, 4.5, 6.3, 10.2, 20.3, 23.4, 23.0, 16.5, 12.0, 6.2]
      }]
    });
  </script>
