 <script>
	
	function validateForm(){
    	var segundos = 5;
		
		var projeto_data_inicio = document.getElementById("projeto_data_inicio").value;
		var projeto_data_previsao_termino = document.getElementById("projeto_data_previsao_termino").value;
		var projeto_data_real_termino = document.getElementById("projeto_data_real_termino").value;
		
	    var data_inicio = new Date(projeto_data_inicio);
	    var data_previsao = new Date(projeto_data_previsao_termino);
	    var data_termino = new Date(projeto_data_real_termino);
	    
	    if (data_inicio > data_previsao) {
		    
	    	document.getElementById('alerta').innerHTML = "A Data de Início deve ser menor que a Previsão de Término!";
	        document.getElementById('alerta').style.display = 'block';
	    		  	    	
	    	setTimeout(function(){
	    	  $('#alerta').fadeOut();
	    	}, segundos*1000);  
	    	   
	        return false;		        
	    }

	    if(projeto_data_inicio == projeto_data_previsao_termino) {
		    
	    	document.getElementById('alerta').innerHTML = "A Data de Início e a Previsão de Término NÃO devem ser iguais!";
	        document.getElementById('alerta').style.display = 'block';
	    		  	    	
	    	setTimeout(function(){
	    	  $('#alerta').fadeOut();
	    	}, segundos*1000);  
	    	   
	        return false;		        
	    }
	    
		if (data_inicio > data_termino || data_inicio === data_termino) {
		    
	    	document.getElementById('alerta').innerHTML = "A Data de Início deve ser menor que a Data de Término!";
	        document.getElementById('alerta').style.display = 'block';
	    		  	    	
	    	setTimeout(function(){
	    	  $('#alerta').fadeOut();
	    	}, segundos*1000);  
	    	   
	        return false;		        
	    } 

	    if(projeto_data_inicio == projeto_data_real_termino) {
		    
	    	document.getElementById('alerta').innerHTML = "A Data de Início e a Data de Término NÃO devem ser iguais!";
	        document.getElementById('alerta').style.display = 'block';
	    		  	    	
	    	setTimeout(function(){
	    	  $('#alerta').fadeOut();
	    	}, segundos*1000);  
	    	   
	        return false;		        
	    } else {
		       $('#projeto_edit').submit(); 
		       return true;
	    }		
	}

</script>

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Projetos</h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Editar Projeto - <?php echo utf8_decode($projeto->projeto_nome); ?><small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">                    
                    <li><a class="link"  href="<?php echo $this->url('projeto'); ?>" ><i class="fa fa-chevron-left" aria-hidden="true"></i> Voltar</a></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>                      
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content">


                  <!-- Smart Wizard -->
                  <p>Esse &eacute; o formul&aacute;rio onde deve ser preenchidas todas as informa&ccedil;&otilde;es do projeto.</p>
                   <form id="projeto_edit" name="projeto_edit"  onSubmit="validateForm(); return false;" method="post" action="<?php echo $this->url('projeto/edit',  array('action'=>'edit', 'id' => $projeto->projeto_id));?>" role="form" class="form-horizontal form-label-left" enctype="multipart/form-data">
                  
                  <div >
                  
                    
                    
                  		<div class="alert alert-danger" id="alerta" name="alerta" style="display: none;">
						  <strong>Erro!</strong> 
						</div> 

                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_nome">T&iacute;tulo <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" id="projeto_nome" name="projeto_nome" value="<?php echo utf8_decode($projeto->projeto_nome); ?>" required="required" class="form-control col-md-7 col-xs-12">
                          	<input type="hidden"  id="projeto_id" name="projeto_id" value="<?php echo utf8_decode($projeto->projeto_nome); ?>">                 	
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_gerente_id">Gerente Respons&aacute;vel <span class="required">*</span>
                          </label>
                          <div class="col-md-4 col-sm-4 col-xs-12">
	                          <select name="projeto_gerente_id" id="projeto_gerente_id"  required="required"  class="form-control col-md-7 col-xs-12">
	                          	<?php 
	                          			foreach($usuarios as $usuario){
	                          				if($usuario->usuario_id == $projeto->projeto_gerente_id){
	                          	?>
	                          			
	                          		<option selected value="<?php echo $usuario->usuario_id; ?>"><?php echo utf8_decode($usuario->usuario_nome); ?></option>
	                          	<?php 
	                          				}else{ ?>
	                          				
	                          		<option value="<?php echo $usuario->usuario_id; ?>"><?php echo utf8_decode($usuario->usuario_nome);?></option>
	                          				
	                          	<?php 
	                          				}
	                          			}
	                          	?>
	                          	</select>
                          	</div>
                        </div>
                        
                        <div class="form-group">
                          <label for="projeto_data_inicio" class="control-label col-md-3 col-sm-3 col-xs-12">Data de in&iacute;cio <span class="required">*</span></label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                          	<input type="hidden" name="projeto_data_inicio_anterior" id="projeto_data_inicio_anterior" value="<?php echo $projeto->projeto_data_inicio; ?>">
                            <input required="required"  id="projeto_data_inicio" value="<?php echo $projeto->projeto_data_inicio; ?>" class="form-control col-md-7 col-xs-12" type="date" name="projeto_data_inicio">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label for="projeto_data_previsao_termino" class="control-label col-md-3 col-sm-3 col-xs-12">Previs&atilde;o de T&eacute;rmino <span class="required">*</span> </label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                          	<input type="hidden" name="projeto_data_previsao_anterior" id="projeto_data_previsao_anterior" value="<?php echo $projeto->projeto_data_previsao_termino; ?>">                           
                            <input required="required" id="projeto_data_previsao_termino" value="<?php echo $projeto->projeto_data_previsao_termino; ?>" class="form-control col-md-7 col-xs-12" type="date" name="projeto_data_previsao_termino">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label for="projeto_data_real_termino" class="control-label col-md-3 col-sm-3 col-xs-12">Data real de T&eacute;rmino</label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                          	<input type="hidden" name="projeto_data_real_termino_anterior" id="projeto_data_real_termino_anterior" value="<?php echo $projeto->projeto_data_real_termino; ?>">                           
                            <input id="projeto_data_real_termino" value="<?php echo $projeto->projeto_data_real_termino; ?>" class="form-control col-md-7 col-xs-12" type="date" name="projeto_data_real_termino">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_orcamento_total">Or&ccedil;amento Total<span class="required">*</span>
                          </label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                            <input type="text" id="projeto_orcamento_total" value="<?php echo $projeto->projeto_orcamento_total; ?>" name="projeto_orcamento_total" required="required" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_descricao">Descri&ccedil;&atilde;o<span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea id="projeto_descricao" name="projeto_descricao" required="required" class="form-control col-md-7 col-xs-12"><?php echo utf8_decode($projeto->projeto_descricao); ?> </textarea>
                          </div>
                        </div>   
                        
                      <?php 
                      $baixoRisco = "";
                      $medioRisco = "";
                      $altoRisco = "";
                      
                      if($projeto->projeto_risco == "Baixo risco"){
                      	$baixoRisco = 'checked=""';                      	
                      }else if($projeto->projeto_risco == "Medio risco"){
                      	$medioRisco = 'checked=""';                                   	
                      }else if($projeto->projeto_risco == "Alto risco"){
                      	$altoRisco = 'checked=""';                          	
                      }
                      
                      ?>
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="riscoRadios">Classifica&ccedil;&atilde;o de Risco<span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            
                             <div class="form-horizontal form-label-left">
	
		                      <div class="col-md-9 col-sm-9 col-xs-12">
		                      	<div class="radio">
		                          <label>
		                            <input required="required" type="radio" <?php echo $baixoRisco; ?> value="Baixo risco" id="Baixo risco" name="riscoRadios"> Baixo risco
		                          </label>
		                        </div>
		                        <div class="radio">
		                          <label>
		                            <input required="required" type="radio" <?php echo $medioRisco; ?> value="Medio risco" id="Medio risco" name="riscoRadios"> M&eacute;dio risco
		                          </label>
		                        </div>
		                        <div class="radio">
		                          <label>
		                            <input required="required" type="radio" <?php echo $altoRisco; ?> value="Alto risco" id="Alto risco" name="riscoRadios"> Alto risco
		                          </label>
		                        </div>
		                      </div>
                    		</div>
                          </div>
                        </div>   
                        
                        <div class="form-group"> 
                          	<label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                        
						    <div class="control-label col-sm-1">
						      <button type="submit" class="btn btn-default">Alterar</button>
						    </div>
						    <div class="control-label col-sm-2">
						        <button type="reset" class="btn btn-default" onclick="location.href='<?php echo $this->url('projeto', array('action'=>'index'));?>'">Cancelar</button>
						   </div>
					  </div>					  
					  
                  </div>
                  </form>
                  <!-- End SmartWizard Content -->

                </div>
              </div>
            </div>

          </div>
        </div>