     <?php 

     use Zend\Session\Container;
     
     ?>
        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Projetos </h3>
            </div>

            <div class="title_right">
              <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                  <input type="text" class="form-control" id="search" placeholder="Procurar por...">
                  <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Buscar!</button>
                        </span>
                </div>
              </div>
            </div>
          </div>
          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Consultar Projetos</h2>
                  <ul class="nav navbar-right panel_toolbox">
                  
		              <?php 
			        	$session_dados = new Container('usuario_dados');
			        	if(isset($session_dados->id)){ 
     						
                        	if(in_array('projeto/add', $session_dados->funcionalidades_usuario)){    	
			        ?>
                    <li>
                    	<a class="link"  href="<?php echo $this->url('projeto/add'); ?>" ><i class="fa fa-plus" aria-hidden="true"></i> Adicionar</a>
                    </li>
                    <?php 	}
     					}?>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content" id="page-selection">

                  <p>Lista todos os projetos</p>
                  
                  <!-- start project list -->
                  <table id="table" class="table table-striped projects">
                    <thead>
                      <tr>
                        <th style="width: 1%">#</th>
                        <th style="width: 20%">Nome</th>
                        <th style="width: 15%">Status</th>
                        <th style="width: 10%">Risco</th>
                        <th style="width: 20%">Edi&ccedil;&atilde;o</th>
                        <th style="width: 20%">A&ccedil;&otilde;es</th>
                      </tr>
                    </thead>
                    
                    <tbody>
                    <?php 

						foreach ($projetos as $projeto)
						{
					?>
					
                      <tr>
                        <td><?php echo $projeto->projeto_id; ?></td>
                        <td>
                          <a><?php echo utf8_decode($projeto->projeto_nome); ?></a>
                          <br />                          
		                    <?php 
		
								$projeto_data_inicio = explode('-', $projeto->projeto_data_inicio);
								
							?>                          
                          <small>In&iacute;cio <?php echo $projeto_data_inicio[2]."/".$projeto_data_inicio[1]."/".$projeto_data_inicio[0]; ?></small>
                        </td>
                        
                        <td><?php echo $projeto->projeto_status; ?></td>
                        <td><?php echo $projeto->projeto_risco; ?></td>
                        <td class="col-md-4 col-sm-4 col-xs-12">
                        
                        <?php if(in_array('projeto/detalhe', $session_dados->funcionalidades_usuario)){ ?>
			                                      
                          <a href="<?php echo $this->url('projeto/detalhe', array('id' => $projeto->projeto_id)); ?>" data-toggle="tooltip" data-placement="top" title="Ver Detalhado" class="btn btn-info btn-xs"><i class="fa fa-folder"></i>  </a>
                          
						<?php }?>
						
                        <?php if(in_array('projeto/edit', $session_dados->funcionalidades_usuario)){ ?>
                          
                          <a href="<?php echo $this->url('projeto/edit', array('id' => $projeto->projeto_id)); ?>" data-toggle="tooltip" data-placement="top" title="Alterar" class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i>  </a>
                          
						<?php }?>
						
                        <?php if(in_array('projeto/delete', $session_dados->funcionalidades_usuario)){ ?>
                          
                          <a href="<?php echo $this->url('projeto/delete', array('id' => $projeto->projeto_id)); ?>" data-toggle="tooltip" data-placement="top" title="Excluir" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i>  </a>
                          
						<?php }?>
						
                        <?php if(in_array('projeto/status', $session_dados->funcionalidades_usuario)){ ?>
                          
                          <a href="<?php echo $this->url('projeto/status', array('id' => $projeto->projeto_id)); ?>" data-toggle="tooltip" data-placement="top" title="Alterar Status" class="btn btn-warning btn-xs"><i class="fa fa-hourglass-half" aria-hidden="true"></i></a>
                        
						<?php }?>
						
                        </td>
                        <td class="col-md-4 col-sm-4 col-xs-12">
                        	
                        <?php if(in_array('indicador_projeto/consulta', $session_dados->funcionalidades_usuario)){ ?>
                        
                          <a href="<?php echo $this->url('indicador_projeto/consulta', array('id' => $projeto->projeto_id)); ?>"  data-toggle="tooltip" data-placement="top" title="Indicadores do Projeto" class="btn btn-info btn-xs"><i class="fa fa-tags" aria-hidden="true"></i></a>
                          	
						<?php }?>
						
                        <?php if(in_array('membro_projeto/consulta', $session_dados->funcionalidades_usuario)){ ?>
                        
                          <a href="<?php echo $this->url('membro_projeto/consulta', array('id' => $projeto->projeto_id)); ?>" data-toggle="tooltip" data-placement="top" title="Membros do Projeto" class="btn btn-info btn-xs"><i class="fa fa-users" aria-hidden="true"></i></a>
                          	
						<?php }?>
						
                        <?php if(in_array('acompanhamento_projeto/consulta', $session_dados->funcionalidades_usuario)){ ?>
                        
                          <a href="<?php echo $this->url('acompanhamento_projeto/consulta', array('id' => $projeto->projeto_id)); ?>" data-toggle="tooltip" data-placement="top" title="Acompanhamentos do Projeto" class="btn btn-info btn-xs"><i class="fa fa-calendar" aria-hidden="true"></i></a>
                          	
						<?php }?>
						
                        <?php if(in_array('tarefa_projeto/consulta', $session_dados->funcionalidades_usuario)){ ?>
                        
                          <a href="<?php echo $this->url('tarefa_projeto/consulta', array('id' => $projeto->projeto_id)); ?>" data-toggle="tooltip" data-placement="top" title="Tarefas do Projeto" class="btn btn-info btn-xs"><i class="fa fa-tasks" aria-hidden="true"></i></a>
                        
						<?php }?>
                        </td>
                      </tr>
                      <?php 
						}
                      ?>                      
                    </tbody>
                  </table>
                  <!-- end project list -->

                </div>
                
		    <script>
		        // init bootpag
		        $('#page-selection').bootpag({
		            total: 10
		        }).on("page", function(event, /* page number here */ num){
		             $("#content").html("Insert content"); // some ajax content loading...
		        });
		    </script>
		    
              </div>
            </div>
          </div>
        </div>

    <script src="//raw.github.com/botmonster/jquery-bootpag/master/lib/jquery.bootpag.min.js"></script>

  <script src="<?php echo $this->basePath('js/bootstrap.min.js'); ?>"></script>

  <!-- chart js -->
  <script src="<?php echo $this->basePath('js/chartjs/chart.min.js'); ?>"></script>
  <!-- bootstrap progress js -->
  <script src="<?php echo $this->basePath('js/progressbar/bootstrap-progressbar.min.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/nicescroll/jquery.nicescroll.min.js'); ?>"></script>
  <!-- icheck -->
  <script src="<?php echo $this->basePath('js/icheck/icheck.min.js'); ?>"></script>

  <script src="<?php echo $this->basePath('js/custom.js'); ?>"></script>

  <!-- pace -->
  <script src="<?php echo $this->basePath('js/pace/pace.min.js'); ?>"></script>
  
  <script>
  $('.demo1').bootpag({
	    total: 5
	}).on("page", function(event, num){
	    $(".content").html("Page " + num); // or some ajax content loading...
	 
	    // ... after content load -> change total to 10
	    $(this).bootpag({total: 10, maxVisible: 10});
	 
	});
</script>


