 <script>
	
	function validateForm(){
		
    	var segundos = 5;	 
	  	var status = getRadioValor('statusRadios');
	  	var justificativa = document.getElementById("projeto_status_justificativa").value;

	  	if(status == "Cancelado" || status == "Analise aprovada"){
		  
		  if(justificativa == ""){
			  	document.getElementById('alerta').innerHTML = "A justificativa é obrigatória para esse Status!";
		        document.getElementById('alerta').style.display = 'block';
		    		  	    	
		    	setTimeout(function(){
		    	  $('#alerta').fadeOut();
		    	}, segundos*1000);  
		    	   
		        return false;
		  }else {
		       $('#projeto_justificativa').submit(); 
		       return true;
	      }
	  
	  	}else {
	       $('#projeto_justificativa').submit(); 
	       return true;
    	}
	}
	  
	  
	 function getRadioValor(name){
	  var rads = document.getElementsByName(name);
	   
	  for(var i = 0; i < rads.length; i++){
	   if(rads[i].checked){
	    return rads[i].value;
	   }
	   
		}
	 }
	   
	 
</script>

	    <!-- page content -->
      <div class="right_col" role="main">

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Projetos</h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Status do Projeto - <?php echo $projeto->projeto_nome; ?><small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="link"  href="<?php echo $this->url('projeto'); ?>" ><i class="fa fa-chevron-left" aria-hidden="true"></i> Voltar</a></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>                      
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content">


                  <!-- Smart Wizard -->
                  <p>Esse é o formulário onde deve ser preenchido o status atual do projeto.</p>
                   <form id="projeto_justificativa" name="projeto_justificativa"  onSubmit="validateForm(); return false;" method="post" action="<?php echo $this->url('projeto/status',  array('action'=>'status', 'id' => $projeto->projeto_id));?>" role="form" class="form-horizontal form-label-left">
                  
                  <div>
                      
                      <?php 
                      $emAnalise = "";
                      $analiseRealizada = "";
                      $analiseAprovada = "";
                      $iniciado = "";
                      $planejado = "";
                      $emAndamento = "";
                      $encerrado = "";
                      $cancelado = "";
                      
                      if($projeto->projeto_status == "Em analise"){
                      	$emAnalise = 'checked=""';                      	
                      }else if($projeto->projeto_status == "Analise realizada"){
                      	$analiseRealizada = 'checked=""';                                   	
                      }else if($projeto->projeto_status == "Analise aprovada"){
                      	$analiseAprovada = 'checked=""';                          	
                      }else if($projeto->projeto_status == "Iniciado"){
                      	$iniciado = 'checked=""';                          	
                      }else if($projeto->projeto_status == "Planejado"){
                      	$planejado = 'checked=""';                          	
                      }else if($projeto->projeto_status == "Em andamento"){
                      	$emAndamento = 'checked=""';                          	
                      }else if($projeto->projeto_status == "Encerrado"){
                      	$encerrado = 'checked=""';                          	
                      }else if($projeto->projeto_status == "Cancelado"){
                      	$cancelado = 'checked=""';                          	
                      }
                      
                      ?>
                  		<div class="alert alert-danger" id="alerta" name="alerta" style="display: none;">
						  <strong>Erro!</strong> 
						</div> 
                      
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="statusRadios">Status<span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                         	<div class="radio">
	                          <label>
	                            <input type="radio"  <?php echo $emAnalise; ?> value="Em analise" id="Em analise" name="statusRadios"> Em análise
	                          </label>
	                        </div>
	                        <div class="radio">
	                          <label>
	                            <input type="radio"  <?php echo $analiseRealizada; ?> value="Analise realizada" id="Analise realizada" name="statusRadios"> Análise realizada
	                          </label>
	                        </div>
	                        <div class="radio">
	                          <label>
	                            <input type="radio"   <?php echo $analiseAprovada; ?> value="Analise aprovada" id="Analise aprovada" name="statusRadios"> Análise aprovada
	                          </label>
	                        </div>
                        
	                        <div class="radio">
	                          <label>
	                            <input type="radio"   <?php echo $iniciado; ?> value="Iniciado" id="Iniciado" name="statusRadios"> Iniciado
	                          </label>
	                        </div>
	                        <div class="radio">
	                          <label>
	                            <input type="radio"  <?php echo $planejado; ?> value="Planejado" id="Planejado" name="statusRadios"> Planejado
	                          </label>
	                        </div>
	                        <div class="radio">
	                          <label>
	                            <input type="radio"  <?php echo $emAndamento; ?> value="Em andamento" id="Em andamento" name="statusRadios"> Em andamento
	                          </label>
	                        </div>
	                        <div class="radio">
	                          <label>
	                            <input type="radio"  <?php echo $encerrado; ?> value="Encerrado" id="Encerrado" name="statusRadios"> Encerrado
	                          </label>
	                        </div>
	                        <div class="radio">
	                          <label>
	                            <input type="radio"  <?php echo $cancelado; ?> value="Cancelado" id="Cancelado" name="statusRadios"> Cancelado
	                          </label>
	                        </div>
                          </div>
                        </div>  
                           
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_status_justificativa">Justificativa
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea id="projeto_status_justificativa" name="projeto_status_justificativa" class="form-control col-md-7 col-xs-12"></textarea>
                          </div>
                        </div> 
                        
                        <div class="form-group"> 
                          	<label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                        
						    <div class="control-label col-sm-1">
						      <button type="submit" class="btn btn-default">Alterar</button>
						    </div>
						    <div class="control-label col-sm-2">
						        <button type="reset" class="btn btn-default" onclick="location.href='<?php echo $this->url('projeto', array('action'=>'index'));?>'">Cancelar</button>
						   </div>
					  </div>					  
					  
                  </div>
                  </form>
                  <!-- End SmartWizard Content -->
                  
                  <!-- ------------Historico de status -->
                  
          <div class="row">
            <div class="col-md-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Histórico</h2>                  
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">

                  <!-- start project list -->
                  <table class="table table-striped projects">
                    <thead>
                      <tr>
                        <th style="width: 15%">Data</th>
                        <th style="width: 15%">Status</th>
                        <th style="width: 10%">Usuário</th>
                      </tr>
                    </thead>
                    
                    <tbody>
                    <?php 

                          $array_usuarios = Array();
                          
                          foreach($usuarios as $usuario){
                          	$array_usuarios[$usuario->usuario_id] = $usuario->usuario_nome;
                          }
                                                    
                          ?>
                    <?php 

						foreach ($justificativas as $justificativa)
						{
					?>
                      <tr>
                        <td><?php echo date('d/m/Y', strtotime($justificativa->projeto_status_data)); ?></td>
                        <td><?php echo $justificativa->projeto_status; ?></td>
                        <td><?php echo $array_usuarios[$justificativa->usuario_id];?></td>
                      </tr>
                      <?php 
						}
                      ?>                      
                    </tbody>
                  </table>
                  <!-- end project list -->

                </div>
              </div>
            </div>
          </div>
          <!-- ----------Historico de status -->

                </div>
              </div>
            </div>

          </div>
        </div>

        <!-- footer content -->
        <footer>
          <div class="copyright-info">
            <p class="pull-right">© 2016 Produzido por Laislla Costa Ramos
            </p>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
      <!-- /page content -->
