
  <div class="">
    <a class="hiddenanchor" id="toregister"></a>
    <a class="hiddenanchor" id="tologin"></a>

    <div id="wrapper">
      <div id="login" class="animate form">
        <section class="login_content">
          <form>
            <h1>Acessar</h1>
            <div>
              <input type="text" class="form-control" placeholder="Nome" required="" />
            </div>
            <div>
              <input type="password" class="form-control" placeholder="Senha" required="" />
            </div>
            <div>
              <a class="btn btn-default submit" href="<?php echo $this->url('projeto', array('action'=>'index'));?>">Acessar</a>
              <a class="reset_pass" href="#">Esqueci minha senha?</a>
            </div>
            <div class="clearfix"></div>
            <div class="separator">

              <p class="change_link">Não possui cadastro?
                <a href="#toregister" class="to_register"> Criar Conta </a>
              </p>
              <div class="clearfix"></div>
              <br />
              <div>
                <h1><i class="fa fa-puzzle-piece" style="font-size: 26px;"></i> Gerenciador de Projetos!</h1>

                <p>© 2016 Produzido por Laislla Costa Ramos</p>
              </div>
            </div>
          </form>
          <!-- form -->
        </section>
        <!-- content -->
      </div>
      <div id="register" class="animate form">
        <section class="login_content">
          <form>
            <h1>Criar Conta</h1>
            <div>
              <input type="text" class="form-control" placeholder="Nome" required="" />
            </div>
            <div>
              <input type="email" class="form-control" placeholder="Email" required="" />
            </div>
            <div>
              <input type="password" class="form-control" placeholder="Senha" required="" />
            </div>
            <div>
              <a class="btn btn-default submit" href="<?php echo $this->url('projeto', array('action'=>'index'));?>">Cadastrar</a>
            </div>
            <div class="clearfix"></div>
            <div class="separator">

              <p class="change_link">Já está cadastrado ?
                <a href="#tologin" class="to_register"> Acessar </a>
              </p>
              <div class="clearfix"></div>
              <br />
              <div>
                <h1><i class="fa fa-puzzle-piece" style="font-size: 26px;"></i> Gerenciador de Projetos!</h1>

                <p>© 2016 Produzido por Laislla Costa Ramos</p>
              </div>
            </div>
          </form>
          <!-- form -->
        </section>
        <!-- content -->
      </div>
    </div>
  </div>