<?php 

use Zend\Session\Container;

?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title><?php echo utf8_encode('Gerenciador de Portifólio de Projetos'); ?></title>

  <!-- Bootstrap core CSS -->

  <link href="css/bootstrap.min.css" rel="stylesheet">

  <link href="fonts/css/font-awesome.min.css" rel="stylesheet">
  <link href="css/animate.min.css" rel="stylesheet">

  <!-- Custom styling plus plugins -->
  <link href="css/custom.css" rel="stylesheet">
  <link href="css/icheck/flat/green.css" rel="stylesheet">


  <script src="js/jquery.min.js"></script>

  <!--[if lt IE 9]>
        <script src="../assets/js/ie8-responsive-file-warning.js"></script>
        <![endif]-->

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

</head>

<body style="background:#F7F7F7;">


  <div class="">
    <a class="hiddenanchor" id="toregister"></a>
    <a class="hiddenanchor" id="tologin"></a>

    <div id="wrapper">
      <div id="login" class="animate form">
        <section class="login_content">
        
          <form  id="loginform" class="" role="form" action="<?php echo $this->url('login', array('action' => 'logar')); ?>" method="post"  enctype="application/x-www-form-urlencoded">
                            <?php

                            $usuario_dados = new Container('usuario_dados');
                            
                            if(isset($_GET['erro'])){
                            if($_GET['erro'] == 1){
                            ?>
                            <div class="alert alert-danger">
							  <strong>Erro!</strong> Email ou senha invalidos!
							</div>
							<?php } }?>
            <h1>Acessar</h1>
            
          <div class="form-group" style="text-align: left;">
		    <label for="email">E-mail</label>
              <input type="text" class="form-control" placeholder="xxxxx@xxxxx.com" id="usuario_email" name="usuario_email" required="required"/>
		  </div>
		  <div class="form-group" style="text-align: left;">
		    <label for="pwd">Senha</label>
              <input type="password" class="form-control" placeholder="******" id="usuario_senha" name="usuario_senha" required="required"  />
		  </div>
		  
                  <!-- 
                   					<div class="input-group">
                                      <div class="checkbox">
                                        <label>
                                          <input id="lembrar" type="checkbox" name="lembrar" value="1"> Lembrar-me
                                        </label>
                                      </div>
                                    </div>
            -->
                                           
		    <div class="control-label col-sm-12" style="text-align: center;">
		      <button type="submit" class="btn btn-default submit">Acessar</button>
		    </div>
            <!--  
            <div>              
              <a class="reset_pass" href="#">Esqueci minha senha?</a>
            </div>
            -->
            <div class="clearfix"></div>
            <div class="separator">

              <p class="change_link"><?php echo utf8_encode('Não possui cadastro?'); ?>
                <a href="#toregister" class="to_register"> Criar Conta </a>
              </p>
              <div class="clearfix"></div>
              <br />
              <div>
                <h1><i class="fa fa-puzzle-piece" style="font-size: 26px;"></i> <?php echo utf8_encode('Gerenciador de Portifólio de Projetos'); ?></h1>

                <p><?php echo utf8_encode('© 2016 Produzido por Laislla Costa Ramos');?></p>
              </div>
            </div>
          </form>
          
          <!-- form -->
        </section>
        <!-- content -->
      </div>
      <div id="register" class="animate form">
        <section class="login_content">
          <form method="post" action="<?php echo $this->url('usuario/add',  array('action'=>'add'));?>" role="form" class="form-horizontal form-label-left">
            <input type="hidden" id="perfi_id" name="perfil_id" value="5">
            <h1>Criar Conta</h1>
            
          <div class="form-group" style="text-align: left;">
		    <label for="email">Nome</label>
              <input type="text" class="form-control" placeholder="Nome" id="usuario_nome" name="usuario_nome" required="required" />
		  </div>
          <div class="form-group" style="text-align: left;">
		    <label for="email">E-mail</label>
              <input type="email" class="form-control" placeholder="Email" id="usuario_email" name="usuario_email" required="required" />
		  </div>
          <div class="form-group" style="text-align: left;">
		    <label for="email">Senha</label>
              <input type="password" class="form-control" placeholder="Senha" id="usuario_senha" name="usuario_senha" required="required" />
		  </div>
		              
		    <div class="control-label col-sm-12" style="text-align: center;">
		      <button type="submit" >Cadastrar</button>
		    </div>
            
            <div class="clearfix"></div>
            <div class="separator">

              <p class="change_link"><?php echo utf8_encode("Já está cadastrado?");?>
                <a href="#tologin" class="to_register"> Acessar </a>
              </p>
              <div class="clearfix"></div>
              <br />
              <div>
                <h1><i class="fa fa-puzzle-piece" style="font-size: 26px;"></i> <?php echo utf8_encode('Gerenciador de Portifólio de Projetos'); ?></h1>

                <p><?php echo utf8_encode("© 2016 Produzido por Laislla Costa Ramos");?></p>
              </div>
            </div>
          </form>
          <!-- form -->
        </section>
        <!-- content -->
      </div>
    </div>
  </div>

</body>

</html>
