<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="iso 8859-1">
        <?php echo $this->headTitle('Gerenciador de Portifólios '. $this->translate('Gerenciador de Portifólios'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        //->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) 

                        ->prependStylesheet($this->basePath('fonts/css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('css/animate.min.css'))

                        ->prependStylesheet($this->basePath('css/custom.css'))
                        ->prependStylesheet($this->basePath('css/maps/jquery-jvectormap-2.0.3.css'))
                        ->prependStylesheet($this->basePath('css/icheck/flat/green.css'))
                        ->prependStylesheet($this->basePath('css/floatexamples.css'))?>                        
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/jquery.min.js'))
            
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/nicescroll/jquery.nicescroll.min.js'))
            ->prependFile($this->basePath('js/chartjs/chart.min.js'))
            ->prependFile($this->basePath('js/progressbar/bootstrap-progressbar.min.js'))
            ->prependFile($this->basePath('js/icheck/icheck.min.js'))
            ->prependFile($this->basePath('js/moment.min2.js'))
            ->prependFile($this->basePath('js/custom.js'))

            ->prependFile($this->basePath('js/flot/jquery.flot.js'))
            ->prependFile($this->basePath('js/flot/jquery.flot.pie.js'))
            ->prependFile($this->basePath('js/flot/jquery.flot.orderBars.js'))
            ->prependFile($this->basePath('js/flot/jquery.flot.time.min.js'))
            ->prependFile($this->basePath('js/flot/date.js'))
            ->prependFile($this->basePath('js/flot/jquery.flot.spline.js'))
            ->prependFile($this->basePath('js/flot/jquery.flot.stack.js'))
            ->prependFile($this->basePath('js/flot/curvedLines.js'))
            ->prependFile($this->basePath('js/flot/jquery.flot.resize.js'))
            ->prependFile($this->basePath('js/pace/pace.min.js'))
            
            ->prependFile($this->basePath('js/datepicker/daterangepicker.js'))
            ->prependFile($this->basePath('js/sparkline/jquery.sparkline.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>


  <link href="<?php echo $this->basePath('css/bootstrap.min.css'); ?>" rel="stylesheet">

  <link href="<?php echo $this->basePath('fonts/css/font-awesome.min.css'); ?>" rel="stylesheet">
  <link href="<?php echo $this->basePath('css/animate.min.css'); ?>" rel="stylesheet">

  <!-- Custom styling plus plugins -->
  <link href="<?php echo $this->basePath('css/custom.css'); ?>" rel="stylesheet">
  <link href="<?php echo $this->basePath('css/icheck/flat/green.css'); ?>" rel="stylesheet">


  <script src="<?php echo $this->basePath('js/jquery.min.js'); ?>"></script>
  
    </head>
	<body class="nav-md">
        <div class="container body">
        
        
            <div class="main_container">

			      <div class="col-md-3 left_col">
			        <div class="left_col scroll-view">
			
			          <div class="navbar nav_title" style="border: 0;">
			            <a href="<?php echo $this->url('application', array('action'=>'index'));?>" class="site_title"><i class="fa fa-puzzle-piece"></i> <span>Portifólio!</span></a>
			          </div>
			          <div class="clearfix"></div>
			
			
			          <!-- menu prile quick info -->
			          <div class="profile" style="padding-bottom: 80px;">
			            <div class="profile_pic">
			              <img src="<?php echo $this->basePath('images/img.jpg'); ?>" alt="..." class="img-circle profile_img">
			            </div>
			            <div class="profile_info">
			              <span>Bem Vindo,</span>
			              <h2>John Doe</h2>
			            </div>
			          </div>
			          <!-- /menu prile quick info -->
			
			          <br />
			
			          <!-- sidebar menu -->
			          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
			
			            <div class="menu_section">
			              <ul class="nav side-menu">
			              
			                <li><a><i class="fa fa-home"></i> Home </a></li>
			                
			                <li><a href="<?php echo $this->url('projeto', array('action'=>'index'));?>" ><i class="fa fa-edit"></i> Projetos </a></li>
			                                
			                <li><a ><i class="fa fa-users"></i> Equipe </a></li>
			                
			                <li><a href="<?php echo $this->url('indicador', array('action'=>'index'));?>"><i class="fa fa-line-chart"></i> Indicadores </a></li>
			                
			                <li><a><i class="fa fa-bar-chart-o"></i> Relatórios </a></li>                
			                
			              </ul>
			            </div> 
			
			          </div>
			          <!-- /sidebar menu -->
			
			          <!-- /menu footer buttons -->
			          <div class="sidebar-footer hidden-small">
			            <a data-toggle="tooltip" data-placement="top" title="Configurações">
			              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
			            </a>
			            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
			              <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
			            </a>
			            <a data-toggle="tooltip" data-placement="top" title="Lock">
			              <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
			            </a>
			            <a data-toggle="tooltip" data-placement="top" title="Sair">
			              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
			            </a>
			          </div>
			          <!-- /menu footer buttons -->
			        </div>
			      </div>
			
			      <!-- top navigation -->
			      <div class="top_nav">
			
			        <div class="nav_menu">
			          <nav class="" role="navigation">
			            <div class="nav toggle">
			              <a id="menu_toggle"><i class="fa fa-bars"></i></a>
			            </div>
			
			            <ul class="nav navbar-nav navbar-right">
			              <li class="">
			                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
			                  <img src="<?php echo $this->basePath('images/img.jpg'); ?>" alt="">John Doe
			                  <span class=" fa fa-angle-down"></span>
			                </a>
			                <ul class="dropdown-menu dropdown-usermenu animated fadeInDown pull-right">
			                  <li><a href="javascript:;">  Perfil</a>
			                  </li>
			                  <li>
			                    <a href="javascript:;">
			                      <span>Configurações</span>
			                    </a>
			                  </li>
			                  <li>
			                    <a href="javascript:;">Ajuda</a>
			                  </li>
			                  <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Sair</a>
			                  </li>
			                </ul>
			              </li>
			
			              <li role="presentation" class="dropdown">
			                <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
			                  <i class="fa fa-envelope-o"></i>
			                  <span class="badge bg-green">6</span>
			                </a>
			                <ul id="menu1" class="dropdown-menu list-unstyled msg_list animated fadeInDown" role="menu">
			                  <li>
			                    <a>
			                      <span class="image">
			                                        <img src="<?php echo $this->basePath('images/img.jpg'); ?>" alt="Profile Image" />
			                                    </span>
			                      <span>
			                                        <span>John Smith</span>
			                      <span class="time">3 mins atrás</span>
			                      </span>
			                      <span class="message">
			                                        Film festivals used to be do-or-die moments for movie makers. They were where...
			                                    </span>
			                    </a>
			                  </li>
			                  
			                  <li>
			                    <div class="text-center">
			                      <a>
			                        <strong>Ver todos os alertas</strong>
			                        <i class="fa fa-angle-right"></i>
			                      </a>
			                    </div>
			                  </li>
			                </ul>
			              </li>
			
			            </ul>
			          </nav>
			        </div>
			
			      </div>
			      <!-- /top navigation --> 
                
        
            <?php echo $this->content; ?>
            
            
    			</div>
    			
    			 <!-- /page content --->
    			
    			
    			
    			
    			
    			
    			
    			
            <hr>
        </div> <!-- /container -->
        
         <div id="custom_notifications" class="custom-notifications dsp_none">
		    <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
		    </ul>
		    <div class="clearfix"></div>
		    <div id="notif-group" class="tabbed_notifications"></div>
		  </div>
        <?php echo $this->inlineScript() ?>
        
  <script src="<?php echo $this->basePath('js/bootstrap.min.js'); ?>"></script>
  
  <script src="<?php echo $this->basePath('js/chartjs/chart.min.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/progressbar/bootstrap-progressbar.min.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/nicescroll/jquery.nicescroll.min.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/icheck/icheck.min.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/custom.js'); ?>"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('js/wizard/jquery.smartWizard.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/pace/pace.min.js'); ?>"></script>
  
  
  <script src="<?php echo $this->basePath('js/bootstrap.min.js'); ?>"></script>

  <!-- chart js -->
  <script src="<?php echo $this->basePath('js/chartjs/chart.min.js'); ?>"></script>
  <!-- bootstrap progress js -->
  <script src="<?php echo $this->basePath('js/progressbar/bootstrap-progressbar.min.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/nicescroll/jquery.nicescroll.min.js'); ?>"></script>
  <!-- icheck -->
  <script src="<?php echo $this->basePath('js/icheck/icheck.min.js'); ?>"></script>

  <script src="<?php echo $this->basePath('js/custom.js'); ?>"></script>

  <!-- pace -->
  <script src="<?php echo $this->basePath('js/pace/pace.min.js'); ?>"></script>
  
  
  <script type="text/javascript">
    $(document).ready(function() {
      // Smart Wizard
      $('#wizard').smartWizard();

      function onFinishCallback() {
        $('#wizard').smartWizard('showMessage', 'Finish Clicked');
        //alert('Finish Clicked');
      }
    });

    $(document).ready(function() {
      // Smart Wizard
      $('#wizard_verticle').smartWizard({
        transitionEffect: 'slide'
      });

    });
  </script>
  
  <!-- flot -->
  <script type="text/javascript">
    //define chart clolors ( you maybe add more colors if you want or flot will add it automatic )
    var chartColours = ['#96CA59', '#3F97EB', '#72c380', '#6f7a8a', '#f7cb38', '#5a8022', '#2c7282'];

    //generate random number for charts
    randNum = function() {
      return (Math.floor(Math.random() * (1 + 40 - 20))) + 20;
    }

    $(function() {
      var d1 = [];
      //var d2 = [];

      //here we generate data for chart
      for (var i = 0; i < 30; i++) {
        d1.push([new Date(Date.today().add(i).days()).getTime(), randNum() + i + i + 10]);
        //    d2.push([new Date(Date.today().add(i).days()).getTime(), randNum()]);
      }

      var chartMinDate = d1[0][0]; //first day
      var chartMaxDate = d1[20][0]; //last day

      var tickSize = [1, "day"];
      var tformat = "%d/%m/%y";

      //graph options
      var options = {
        grid: {
          show: true,
          aboveData: true,
          color: "#3f3f3f",
          labelMargin: 10,
          axisMargin: 0,
          borderWidth: 0,
          borderColor: null,
          minBorderMargin: 5,
          clickable: true,
          hoverable: true,
          autoHighlight: true,
          mouseActiveRadius: 100
        },
        series: {
          lines: {
            show: true,
            fill: true,
            lineWidth: 2,
            steps: false
          },
          points: {
            show: true,
            radius: 4.5,
            symbol: "circle",
            lineWidth: 3.0
          }
        },
        legend: {
          position: "ne",
          margin: [0, -25],
          noColumns: 0,
          labelBoxBorderColor: null,
          labelFormatter: function(label, series) {
            // just add some space to labes
            return label + '&nbsp;&nbsp;';
          },
          width: 40,
          height: 1
        },
        colors: chartColours,
        shadowSize: 0,
        tooltip: true, //activate tooltip
        tooltipOpts: {
          content: "%s: %y.0",
          xDateFormat: "%d/%m",
          shifts: {
            x: -30,
            y: -50
          },
          defaultTheme: false
        },
        yaxis: {
          min: 0
        },
        xaxis: {
          mode: "time",
          minTickSize: tickSize,
          timeformat: tformat,
          min: chartMinDate,
          max: chartMaxDate
        }
      };
      var plot = $.plot($("#placeholder33x"), [{
        label: "Email Sent",
        data: d1,
        lines: {
          fillColor: "rgba(150, 202, 89, 0.12)"
        }, //#96CA59 rgba(150, 202, 89, 0.42)
        points: {
          fillColor: "#fff"
        }
      }], options);
    });
  </script>
  <!-- /flot -->
  <!--  -->
  <script>
    $('document').ready(function() {
      $(".sparkline_one").sparkline([2, 4, 3, 4, 5, 4, 5, 4, 3, 4, 5, 6, 4, 5, 6, 3, 5, 4, 5, 4, 5, 4, 3, 4, 5, 6, 7, 5, 4, 3, 5, 6], {
        type: 'bar',
        height: '125',
        barWidth: 13,
        colorMap: {
          '7': '#a1a1a1'
        },
        barSpacing: 2,
        barColor: '#26B99A'
      });

      $(".sparkline11").sparkline([2, 4, 3, 4, 5, 4, 5, 4, 3, 4, 6, 2, 4, 3, 4, 5, 4, 5, 4, 3], {
        type: 'bar',
        height: '40',
        barWidth: 8,
        colorMap: {
          '7': '#a1a1a1'
        },
        barSpacing: 2,
        barColor: '#26B99A'
      });

      $(".sparkline22").sparkline([2, 4, 3, 4, 7, 5, 4, 3, 5, 6, 2, 4, 3, 4, 5, 4, 5, 4, 3, 4, 6], {
        type: 'line',
        height: '40',
        width: '200',
        lineColor: '#26B99A',
        fillColor: '#ffffff',
        lineWidth: 3,
        spotColor: '#34495E',
        minSpotColor: '#34495E'
      });

      var doughnutData = [{
        value: 30,
        color: "#455C73"
      }, {
        value: 30,
        color: "#9B59B6"
      }, {
        value: 60,
        color: "#BDC3C7"
      }, {
        value: 100,
        color: "#26B99A"
      }, {
        value: 120,
        color: "#3498DB"
      }];
      var myDoughnut = new Chart(document.getElementById("canvas1i").getContext("2d")).Doughnut(doughnutData);
      var myDoughnut = new Chart(document.getElementById("canvas1i2").getContext("2d")).Doughnut(doughnutData);
      var myDoughnut = new Chart(document.getElementById("canvas1i3").getContext("2d")).Doughnut(doughnutData);
    });
  </script>
  <!-- -->
  <!-- datepicker -->
  <script type="text/javascript">
    $(document).ready(function() {

      var cb = function(start, end, label) {
        console.log(start.toISOString(), end.toISOString(), label);
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        //alert("Callback has fired: [" + start.format('MMMM D, YYYY') + " to " + end.format('MMMM D, YYYY') + ", label = " + label + "]");
      }

      var optionSet1 = {
        startDate: moment().subtract(29, 'days'),
        endDate: moment(),
        minDate: '01/01/2012',
        maxDate: '12/31/2015',
        dateLimit: {
          days: 60
        },
        showDropdowns: true,
        showWeekNumbers: true,
        timePicker: false,
        timePickerIncrement: 1,
        timePicker12Hour: true,
        ranges: {
          'Today': [moment(), moment()],
          'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
          'Last 7 Days': [moment().subtract(6, 'days'), moment()],
          'Last 30 Days': [moment().subtract(29, 'days'), moment()],
          'This Month': [moment().startOf('month'), moment().endOf('month')],
          'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        opens: 'left',
        buttonClasses: ['btn btn-default'],
        applyClass: 'btn-small btn-primary',
        cancelClass: 'btn-small',
        format: 'MM/DD/YYYY',
        separator: ' to ',
        locale: {
          applyLabel: 'Submit',
          cancelLabel: 'Clear',
          fromLabel: 'From',
          toLabel: 'To',
          customRangeLabel: 'Custom',
          daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
          monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
          firstDay: 1
        }
      };
      $('#reportrange span').html(moment().subtract(29, 'days').format('MMMM D, YYYY') + ' - ' + moment().format('MMMM D, YYYY'));
      $('#reportrange').daterangepicker(optionSet1, cb);
      $('#reportrange').on('show.daterangepicker', function() {
        console.log("show event fired");
      });
      $('#reportrange').on('hide.daterangepicker', function() {
        console.log("hide event fired");
      });
      $('#reportrange').on('apply.daterangepicker', function(ev, picker) {
        console.log("apply event fired, start/end dates are " + picker.startDate.format('MMMM D, YYYY') + " to " + picker.endDate.format('MMMM D, YYYY'));
      });
      $('#reportrange').on('cancel.daterangepicker', function(ev, picker) {
        console.log("cancel event fired");
      });
      $('#options1').click(function() {
        $('#reportrange').data('daterangepicker').setOptions(optionSet1, cb);
      });
      $('#options2').click(function() {
        $('#reportrange').data('daterangepicker').setOptions(optionSet2, cb);
      });
      $('#destroy').click(function() {
        $('#reportrange').data('daterangepicker').remove();
      });
    });
  </script>
  <!-- /datepicker -->
        
    </body>
</html>
