    <div class="main_container">

      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">

          <div class="navbar nav_title" style="border: 0;">
            <a href="<?php echo $this->url('application', array('action'=>'index'));?>" class="site_title"><i class="fa fa-puzzle-piece"></i> <span>Portifólio!</span></a>
          </div>
          <div class="clearfix"></div>


          <!-- menu prile quick info -->
          <div class="profile" style="padding-bottom: 80px;">
            <div class="profile_pic">
              <img src="<?php echo $this->basePath('images/img.jpg'); ?>" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>Bem Vindo,</span>
              <h2>John Doe</h2>
            </div>
          </div>
          <!-- /menu prile quick info -->

          <br />

          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

            <div class="menu_section">
              <ul class="nav side-menu">
              
                <li><a><i class="fa fa-home"></i> Home </a></li>
                
                <li><a><i class="fa fa-edit"></i> Projetos </a></li>
                                
                <li><a><i class="fa fa-users"></i> Equipe </a></li>
                
                <li><a><i class="fa fa-line-chart"></i> Indicadores </a></li>
                
                <li><a><i class="fa fa-bar-chart-o"></i> Relatórios </a></li>                
                
              </ul>
            </div> 

          </div>
          <!-- /sidebar menu -->

          <!-- /menu footer buttons -->
          <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Configurações">
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
              <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
              <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Sair">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
          </div>
          <!-- /menu footer buttons -->
        </div>
      </div>

      <!-- top navigation -->
      <div class="top_nav">

        <div class="nav_menu">
          <nav class="" role="navigation">
            <div class="nav toggle">
              <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
              <li class="">
                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <img src="<?php echo $this->basePath('images/img.jpg'); ?>" alt="">John Doe
                  <span class=" fa fa-angle-down"></span>
                </a>
                <ul class="dropdown-menu dropdown-usermenu animated fadeInDown pull-right">
                  <li><a href="javascript:;">  Perfil</a>
                  </li>
                  <li>
                    <a href="javascript:;">
                      <span>Configurações</span>
                    </a>
                  </li>
                  <li>
                    <a href="javascript:;">Ajuda</a>
                  </li>
                  <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Sair</a>
                  </li>
                </ul>
              </li>

              <li role="presentation" class="dropdown">
                <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                  <i class="fa fa-envelope-o"></i>
                  <span class="badge bg-green">6</span>
                </a>
                <ul id="menu1" class="dropdown-menu list-unstyled msg_list animated fadeInDown" role="menu">
                  <li>
                    <a>
                      <span class="image">
                                        <img src="<?php echo $this->basePath('images/img.jpg'); ?>" alt="Profile Image" />
                                    </span>
                      <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins atrás</span>
                      </span>
                      <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
                    </a>
                  </li>
                  
                  <li>
                    <div class="text-center">
                      <a>
                        <strong>Ver todos os alertas</strong>
                        <i class="fa fa-angle-right"></i>
                      </a>
                    </div>
                  </li>
                </ul>
              </li>

            </ul>
          </nav>
        </div>

      </div>
      <!-- /top navigation -->

      <!-- page content -------------------------------------------------------------------------------------------------------------------------------------->
      <div class="right_col" role="main">

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Projeto</h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Novo Projeto <small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"></a>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>                      
                    </li>
                    <li><a href="<?php echo $this->url('application', array('action'=>'index'));?>" class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content">


                  <!-- Smart Wizard -->
                  <p>Esse é o formulário onde deve ser preenchidas todas as informações do novo projeto.</p>
                  <div id="wizard" class="form_wizard wizard_horizontal">
                    <ul class="wizard_steps">
                      <li>
                        <a href="#step-1">
                          <span class="step_no">1</span>
                          <span class="step_descr">
                                            Dados<br />
                                            <small>Dados Gerais do Projeto</small>
                                        </span>
                        </a>
                      </li>
                      <li>
                        <a href="#step-2">
                          <span class="step_no">2</span>
                          <span class="step_descr">
                                            Classificação<br />
                                            <small>Classificação do projeto</small>
                                        </span>
                        </a>
                      </li>
                      <li>
                        <a href="#step-3">
                          <span class="step_no">3</span>
                          <span class="step_descr">
                                            Status<br />
                                            <small>Status do projeto</small>
                                        </span>
                        </a>
                      </li>
                      <li>
                        <a href="#step-4">
                          <span class="step_no">4</span>
                          <span class="step_descr">
                                            Revisão<br />
                                            <small>Finalize o cadastro do projeto</small>
                                        </span>
                        </a>
                      </li>
                    </ul>
                    <div id="step-1">
                      <form class="form-horizontal form-label-left">

                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Título <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" id="first-name" required="required" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Gerente Responsável <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" id="last-name" name="last-name" required="required" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Data de início <span class="required">*</span></label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input id="middle-name" class="form-control col-md-7 col-xs-12" type="date" name="middle-name">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Previsão de Término <span class="required">*</span> </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input id="middle-name" class="form-control col-md-7 col-xs-12" type="date" name="middle-name">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Data real de término</label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input id="middle-name" class="form-control col-md-7 col-xs-12" type="date" name="middle-name">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Orçamento Total<span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" id="last-name" name="last-name" required="required" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Descrição<span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea id="last-name" name="last-name" required="required" class="form-control col-md-7 col-xs-12"></textarea>
                          </div>
                        </div>

                      </form>

                    </div>
                    
                    <div id="step-2">
                      <h2 class="StepTitle">Classificação de Risco</h2>
                      
                      
                      <div class="form-horizontal form-label-left">
	
	                      <div class="col-md-9 col-sm-9 col-xs-12">
	                      	<div class="radio">
	                          <label>
	                            <input type="radio" checked="" value="option1" id="optionsRadios1" name="optionsRadios"> Baixo risco
	                          </label>
	                        </div>
	                        <div class="radio">
	                          <label>
	                            <input type="radio" value="option2" id="optionsRadios2" name="optionsRadios"> Médio risco
	                          </label>
	                        </div>
	                        <div class="radio">
	                          <label>
	                            <input type="radio" value="option2" id="optionsRadios2" name="optionsRadios"> Alto risco
	                          </label>
	                        </div>
	                      </div>
                    	</div>
                      
                    </div>
                    
                    <div id="step-3">
                      <h2 class="StepTitle">Status</h2>
                      
                      <div class="form-horizontal form-label-left">
	                      <div class="col-md-9 col-sm-9 col-xs-12">
	                      	<div class="radio">
	                          <label>
	                            <input type="radio" checked="" value="option1" id="optionsRadios1" name="optionsRadios"> em análise
	                          </label>
	                        </div>
	                        <div class="radio">
	                          <label>
	                            <input type="radio" value="option2" id="optionsRadios2" name="optionsRadios"> análise realizada
	                          </label>
	                        </div>
	                        <div class="radio">
	                          <label>
	                            <input type="radio" value="option2" id="optionsRadios2" name="optionsRadios"> análise aprovada
	                          </label>
	                        </div>
	                        <div class="radio">
	                          <label>
	                            <input type="radio" value="option2" id="optionsRadios2" name="optionsRadios"> iniciado
	                          </label>
	                        </div>
	                        <div class="radio">
	                          <label>
	                            <input type="radio" value="option2" id="optionsRadios2" name="optionsRadios"> planejado
	                          </label>
	                        </div>
	                        <div class="radio">
	                          <label>
	                            <input type="radio" value="option2" id="optionsRadios2" name="optionsRadios"> em andamento
	                          </label>
	                        </div>
	                        <div class="radio">
	                          <label>
	                            <input type="radio" value="option2" id="optionsRadios2" name="optionsRadios"> encerrado
	                          </label>
	                        </div>
	                        <div class="radio">
	                          <label>
	                            <input type="radio" value="option2" id="optionsRadios2" name="optionsRadios"> cancelado
	                          </label>
	                        </div>
	                      </div>
                    	</div>
                      
                    </div>
                    
                    <div id="step-4">
                      <h2 class="StepTitle">Revisão</h2>
                      
                        <div class="form-group">
                          <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Título: 
                          </label>
                          <div class="col-md-10 col-sm-10 col-xs-12">
                            Gerenciador de portifólios
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Gerente responsável: 
                          </label>
                          <div class="col-md-10 col-sm-10 col-xs-12">
                            Laislla Ramos
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Data de início: 
                          </label>
                          <div class="col-md-10 col-sm-10 col-xs-12">
                            20/05/2016
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Previsão de término: 
                          </label>
                          <div class="col-md-10 col-sm-10 col-xs-12">
                            01/08/2016
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Data real de término: 
                          </label>
                          <div class="col-md-10 col-sm-10 col-xs-12">
                            --
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Orçamento Total: 
                          </label>
                          <div class="col-md-10 col-sm-10 col-xs-12">
                            R$ 0,00
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Descrição: 
                          </label>
                          <div class="col-md-10 col-sm-10 col-xs-12">
                            Esse é um projeto teste.
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Risco: 
                          </label>
                          <div class="col-md-10 col-sm-10 col-xs-12">
                            Baixo Risco
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Status: 
                          </label>
                          <div class="col-md-10 col-sm-10 col-xs-12">
                            Iniciado
                          </div>
                        </div>
                      
                    </div>

                  </div>
                  <!-- End SmartWizard Content -->

                </div>
              </div>
            </div>

          </div>
        </div>

        <!-- footer content -->
        <footer>
          <div class="copyright-info">
            <p class="pull-right">© 2016 Produzido por Laislla Costa Ramos
            </p>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
      <!-- /page content -------------------------------------------------------------------------------------------------------------------------------------->
    </div>
