  <script>
	
	function validateForm(){
    	var segundos = 5;
		
		var valor_minimo = document.getElementById("valor_minimo").value;
		var valor_maximo = document.getElementById("valor_maximo").value;
			    
	    if (valor_minimo > valor_maximo) {
		    
	    	document.getElementById('alerta').innerHTML = "O valor mínimo deve ser menor que o valor máximo!";
	        document.getElementById('alerta').style.display = 'block';
	    		  	    	
	    	setTimeout(function(){
	    	  $('#alerta').fadeOut();
	    	}, segundos*1000);  
	    	   
	        return false;		        
	    }

	    if (valor_minimo == valor_maximo) {
		    
	    	document.getElementById('alerta').innerHTML = "O valor mínimo deve ser menor que o valor máximo!";
	        document.getElementById('alerta').style.display = 'block';
	    		  	    	
	    	setTimeout(function(){
	    	  $('#alerta').fadeOut();
	    	}, segundos*1000);  
	    	   
	        return false;		        
	    }else {
		       $('#indicador_add').submit(); 
		       return true;
	    }		
	}

</script>

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Indicadores do Projeto - <?php echo utf8_decode($projeto->projeto_nome);?></h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Adicionar Indicador a  <?php echo utf8_decode($projeto->projeto_nome);?> <small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="link"  href="<?php echo $this->url('indicador_projeto/consulta', array('id' => $projeto->projeto_id)); ?>" ><i class="fa fa-chevron-left" aria-hidden="true"></i> Voltar</a></li>
                    
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content">


                  <!-- Smart Wizard -->
                  <p>Esse &eacute; o formul&aacute;rio onde deve ser preenchidas todas as informa&ccedil;&otilde;es do novo indicador.</p>
                  
  				<form  id="indicador_add" name="indicador_add"  onSubmit="validateForm(); return false;" method="post" action="<?php echo $this->url('indicador_projeto/add', array('id' => $id));?>" role="form" class="form-horizontal form-label-left">
              
                  <div>
                  		<div class="alert alert-danger" id="alerta" name="alerta" style="display: none;">
						  <strong>Erro!</strong> 
						</div> 
						
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_id">Indicador <span class="required">*</span>
                          </label>
                          <div class="col-md-4 col-sm-6 col-xs-12">
                          	<select name="indicador_id" id="indicador_id"  required="required"  class="form-control col-md-7 col-xs-12">
                          	<?php 
                          		foreach($indicadores as $indicador)
                          		{
                          	?>
                          		<option value="<?php echo $indicador->indicador_id; ?>"><?php echo utf8_decode($indicador->indicador_nome); ?></option>
                          	<?php 
                          		}
                          	
                          	?>
                          	</select>
                          </div>
                        </div>                        
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_fase">Fase <span class="required">*</span>
                          </label>
                          <div class="col-md-3 col-sm-6 col-xs-12">
                          	<select name="projeto_fase" id="projeto_fase"  required="required"  class="form-control col-md-7 col-xs-12">
                          		<option value="Iniciacao">Inicia&ccedil;&atilde;o</option>
                          		<option value="Planejamento">Planejamento</option>
                          		<option value="Execucao">Execu&ccedil;&atilde;o</option>
                          		<option value="Monitoramento e Controle">Monitoramento e Controle</option>
                          		<option value="Encerramento">Encerramento</option>
                          	</select>
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="valor_minimo">Valor M&iacute;nimo <span class="required">*</span>
                          </label>
                          <div class="col-md-2 col-sm-6 col-xs-12">
                            <input type="number" id="valor_minimo" name="valor_minimo" required="required" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="valor_maximo">Valor m&aacute;ximo <span class="required">*</span>
                          </label>
                          <div class="col-md-2 col-sm-6 col-xs-12">
                            <input type="number" id="valor_maximo" name="valor_maximo" required="required" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>				  
					  
                        <div class="form-group"> 
                          	<label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                        
						    <div class="control-label col-sm-1">
						      <button type="submit" class="btn btn-default">Cadastrar</button>
						    </div>
						    <div class="control-label col-sm-2">
						       <button type="reset" class="btn btn-default" onclick="location.href='<?php echo $this->url('indicador_projeto/consulta', array('action'=>'consulta', 'id' => $id));?>'">Cancelar</button>
						     </div>
					  </div>
					  
                  </div>
                  </form>
                  <!-- End SmartWizard Content -->

                </div>
              </div>
            </div>

          </div>
        </div>