       <!-- page content -->
      <div class="right_col" role="main">

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Indicadores do Projeto</h3>
            </div>

            <div class="title_right">
              <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search for...">
                  <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Buscar!</button>
                        </span>
                </div>
              </div>
            </div>
          </div>
          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Indicadores de <?php echo $projeto->projeto_nome;?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="link"  href="<?php echo $this->url('indicador_projeto/add', array('id' => $id));?>" ><i class="fa fa-plus" aria-hidden="true"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">

                  <p>Lista todos os indicadores do projeto</p>

                  <!-- start project list -->
                  <table class="table table-striped projects">
                    <thead>
                      <tr>
                        <th style="width: 20%">Indicador</th>
                        <th style="width: 20%">Fase</th>
                        <th style="width: 10%">Valor mínimo</th>
                        <th style="width: 15%">Valor máximo</th>
                        <th style="width: 10%">Valor</th>
                        <th style="width: 20%">Edição</th>
                      </tr>
                    </thead>
                    
                    <tbody>
                    <?php 

                    $array_indicadores = Array();
                    
                    foreach($indicadores as $indicador){
                    	$array_indicadores[$indicador->indicador_id] = $indicador->indicador_nome;
                    }
                    
						foreach ($indicadoresProjeto as $indicador)
						{
							
							if(is_object($indicador)){
					?>
                      <tr>
                        <td><?php echo utf8_decode($array_indicadores[$indicador->indicador_id]); ?></td>
                        <td><?php echo utf8_decode($indicador->projeto_fase); ?></td>
                        <td><?php echo $indicador->valor_minimo; ?></td>
                        <td><?php echo $indicador->valor_maximo; ?></td>
                        <td><?php echo $indicador->indicador_projeto_valor; ?></td>
                        <td>
                          <a href="<?php echo $this->url('indicador_projeto/detalhe', array('id' => $indicador->indicador_projeto_id)); ?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i>  </a>
                          <a href="<?php echo $this->url('indicador_projeto/edit', array('projeto_id' => $id, 'id' => $indicador->indicador_projeto_id)); ?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>  </a>
                          <a href="<?php echo $this->url('indicador_projeto/delete', array('projeto_id' => $id, 'id' => $indicador->indicador_projeto_id)); ?>" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i>  </a>
                          <a href="<?php echo $this->url('indicador_projeto/analise', array('projeto_id' => $id, 'id' => $indicador->indicador_projeto_id)); ?>" class="btn btn-info btn-xs"><i class="fa fa-line-chart"></i>  </a>
                        </td>
                      </tr>
                      <?php 
							}
						}
                      ?>                      
                    </tbody>
                  </table>
                  <!-- end project list -->

                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- footer content -->
        <footer>
          <div class="copyright-info">
            <p class="pull-right">Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
            </p>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
      <!-- /page content -->

  <script src="<?php echo $this->basePath('js/bootstrap.min.js'); ?>"></script>

  <!-- chart js -->
  <script src="<?php echo $this->basePath('js/chartjs/chart.min.js'); ?>"></script>
  <!-- bootstrap progress js -->
  <script src="<?php echo $this->basePath('js/progressbar/bootstrap-progressbar.min.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/nicescroll/jquery.nicescroll.min.js'); ?>"></script>
  <!-- icheck -->
  <script src="<?php echo $this->basePath('js/icheck/icheck.min.js'); ?>"></script>

  <script src="<?php echo $this->basePath('js/custom.js'); ?>"></script>

  <!-- pace -->
  <script src="<?php echo $this->basePath('js/pace/pace.min.js'); ?>"></script>


