<?php 
     use Zend\Session\Container;  
	 $session_dados = new Container('usuario_dados');   
 ?>  
        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Indicadores do Projeto - <?php echo utf8_decode($projeto->projeto_nome); ?></h3>
            </div>
          </div>
          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Consultar Indicadores de <?php echo utf8_decode($projeto->projeto_nome);?></h2>
                  <ul class="nav navbar-right panel_toolbox">
                  
		              <?php if(in_array('indicador_projeto/add', $session_dados->funcionalidades_usuario)){ ?>
                    <li>
                    	<a class="link"  href="<?php echo $this->url('indicador_projeto/add', array('id' => $id));?>" ><i class="fa fa-plus" aria-hidden="true"></i> Adicionar</a>
                    </li>
                    <?php 	} ?>
                    <li><a class="link"  href="<?php echo $this->url('projeto', array('id' => $projeto->projeto_id)); ?>" ><i class="fa fa-chevron-left" aria-hidden="true"></i> Voltar</a></li>
                   
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content" class="table-responsive">

                  <p>Lista todos os indicadores do projeto</p>

                  <!-- start project list -->
                  <table  id="minhatabela" class="table table-striped">
                    <thead>
                      <tr>
                        <th style="width: 20%">Indicador</th>
                        <th style="width: 20%">Fase</th>
                        <th style="width: 10%">Valor m&iacute;nimo</th>
                        <th style="width: 15%">Valor m&aacute;ximo</th>
                        <th style="width: 10%">Valor</th>
                        <th style="width: 20%">Edi&ccedil;&atilde;o</th>
                      </tr>
                    </thead>
                    
                    <tbody>
                    <?php 

                    $array_indicadores = Array();
                    
                    foreach($indicadores as $indicador){
                    	$array_indicadores[$indicador->indicador_id] = $indicador->indicador_nome;
                    }
                    
						foreach ($indicadoresProjeto as $indicador)
						{
							
							if(is_object($indicador)){
					?>
                      <tr>
                        <td><?php echo utf8_decode($array_indicadores[$indicador->indicador_id]); ?></td>
                        <td><?php echo utf8_decode($indicador->projeto_fase); ?></td>
                        <td><?php echo $indicador->valor_minimo; ?></td>
                        <td><?php echo $indicador->valor_maximo; ?></td>
                        <td><?php echo $indicador->indicador_projeto_valor; ?></td>
                        <td>
		              <?php if(in_array('indicador_projeto/detalhe', $session_dados->funcionalidades_usuario)){ ?>
                          <a href="<?php echo $this->url('indicador_projeto/detalhe', array('projeto_id' => $id, 'id' => $indicador->indicador_projeto_id)); ?>" data-toggle="tooltip" data-placement="top" title="Ver Detalhado" class="btn btn-info btn-xs"><i class="fa fa-folder"></i>  </a>
                      <?php } ?>
                    
		              <?php if(in_array('indicador_projeto/edit', $session_dados->funcionalidades_usuario)){ ?>
                          <a href="<?php echo $this->url('indicador_projeto/edit', array('projeto_id' => $id, 'id' => $indicador->indicador_projeto_id)); ?>" data-toggle="tooltip" data-placement="top" title="Alterar" class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i>  </a>
                      <?php } ?>   
		              <?php if(in_array('indicador_projeto/delete', $session_dados->funcionalidades_usuario)){ ?>
                          <a href="<?php echo $this->url('indicador_projeto/delete', array('projeto_id' => $id, 'id' => $indicador->indicador_projeto_id)); ?>" data-toggle="tooltip" data-placement="top" title="Excluir" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i>  </a>
                      <?php } ?>
		              <?php if(in_array('indicador_projeto/analise', $session_dados->funcionalidades_usuario)){ ?>
		              	  <a href="<?php echo $this->url('indicador_projeto/analise', array('projeto_id' => $id, 'id' => $indicador->indicador_projeto_id)); ?>" data-toggle="tooltip" data-placement="top" title="Analisar" class="btn btn-warning btn-xs"><i class="fa fa-line-chart"></i>  </a>
                      <?php }?>  
                        </td>
                      </tr>
                      <?php 
							}
						}
                      ?>                      
                    </tbody>
                  </table>
                  <!-- end project list -->

                </div>
              </div>
            </div>
          </div>
        </div>

  <script src="<?php echo $this->basePath('js/bootstrap.min.js'); ?>"></script>

  <!-- chart js -->
  <script src="<?php echo $this->basePath('js/chartjs/chart.min.js'); ?>"></script>
  <!-- bootstrap progress js -->
  <script src="<?php echo $this->basePath('js/progressbar/bootstrap-progressbar.min.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/nicescroll/jquery.nicescroll.min.js'); ?>"></script>
  <!-- icheck -->
  <script src="<?php echo $this->basePath('js/icheck/icheck.min.js'); ?>"></script>

  <script src="<?php echo $this->basePath('js/custom.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/jquery.dataTables.min.js'); ?>"></script>

  <!-- pace -->
  <script src="<?php echo $this->basePath('js/pace/pace.min.js'); ?>"></script>
  
		    <script>
			    $(document).ready(function(){
			        $('#minhatabela').dataTable();
			    });
		        
		    </script>
  


