<?php

 $title = 'Visualizar Indicador do Projeto '.$projeto->projeto_nome;
 $this->headTitle($title);
 ?>
 
       <!-- page content -->
      <div class="right_col" role="main">

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Indicadores do Projeto - <?php echo $projeto->projeto_nome; ?></h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12" style="text-align: center;">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2><?php echo $title;?> <small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="link"  href="<?php echo $this->url('indicador_projeto/consulta', array('id' => $projeto->projeto_id)); ?>" ><i class="fa fa-chevron-left" aria-hidden="true"></i> Voltar</a></li>
                   <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>                      
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content"> 
 
                  <!-- Smart Wizard --> 
                  
  				<form action="" method="post" role="form" class="form-horizontal form-label-left">
                   						<?php 

                   						$array_indicadores = Array();
                   						
                   						foreach($indicadores as $indicador){
                   							$array_indicadores[$indicador->indicador_id] = $indicador->indicador_nome;
                   						}
                   						
                   						?>
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome">Título:
                          </label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">
                          <label class="control-label "><?php echo $array_indicadores[$indicadorProjeto->indicador_id]; ?>
                          </label>      	
                          </div>
                        </div>		
                        	
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome">Fase: </label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">                          
                          	<label class="control-label"><?php echo utf8_decode($indicadorProjeto->projeto_fase); ?></label>  
                          </div>
                        </div>	
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome">Valor mínimo:</label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">
                          	<label class="control-label"><?php echo $indicadorProjeto->valor_minimo; ?></label>      	
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome">Valor máximo:</label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">
                          	<label class="control-label"><?php echo $indicadorProjeto->valor_maximo; ?></label>      	
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome">Valor:</label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">
                          	<label class="control-label"><?php echo $indicadorProjeto->indicador_projeto_valor; ?></label>      	
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome">Análise:</label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">
                          	<label class="control-label"><?php echo $indicadorProjeto->indicador_projeto_descricao; ?></label>      	
                          </div>
                        </div>
                  
                  </form>
                  <!-- End SmartWizard Content -->

                </div>
              </div>
            </div>

          </div>
        </div>

        <!-- footer content -->
        <footer>
          <div class="copyright-info">
            <p class="pull-right">© 2016 Produzido por Laislla Costa Ramos
            </p>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
      <!-- /page content -->
                  
 
