  <script>
	
	function validateForm(){
    	var segundos = 5;
		
		var valor_minimo = document.getElementById("valor_minimo").value;
		var valor_maximo = document.getElementById("valor_maximo").value;
			    
	    if (valor_minimo > valor_maximo) {
		    
	    	document.getElementById('alerta').innerHTML = "O valor mínimo deve ser menor que o valor máximo!";
	        document.getElementById('alerta').style.display = 'block';
	    		  	    	
	    	setTimeout(function(){
	    	  $('#alerta').fadeOut();
	    	}, segundos*1000);  
	    	   
	        return false;		        
	    }

	    if (valor_minimo == valor_maximo) {
		    
	    	document.getElementById('alerta').innerHTML = "O valor mínimo deve ser menor que o valor máximo!";
	        document.getElementById('alerta').style.display = 'block';
	    		  	    	
	    	setTimeout(function(){
	    	  $('#alerta').fadeOut();
	    	}, segundos*1000);  
	    	   
	        return false;		        
	    }else {
		       $('#indicador_edit').submit(); 
		       return true;
	    }		
	}

</script>
      <!-- page content -->
      <div class="right_col" role="main">

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Associar Indicador a Projeto</h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Editar Indicador de  <?php echo $projeto->projeto_nome;?> <small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"></a>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>                      
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content">


                  <!-- Smart Wizard -->
                  <p>Esse é o formulário onde deve ser preenchidas todas as informações do indicador.</p>
                  
                   <form  id="indicador_edit" name="indicador_edit"  onSubmit="validateForm(); return false;"  method="post" action="<?php echo $this->url('indicador_projeto/edit',  array('action'=>'edit','projeto_id' => $projeto_id, 'id' => $indicadorProjeto->indicador_projeto_id));?>" role="form" class="form-horizontal form-label-left">
                   		
                   		<input type="hidden" id="indicador_projeto_valor" name="indicador_projeto_valor" value="<?php echo $indicadorProjeto->indicador_projeto_valor;?>">
                        <input type="hidden" id="indicador_projeto_descricao" name="indicador_projeto_descricao" value="<?php echo $indicadorProjeto->indicador_projeto_descricao;?>">
                       
                  <div>
                  		<div class="alert alert-danger" id="alerta" name="alerta" style="display: none;">
						  <strong>Erro!</strong> 
						</div> 

                       <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_id">Indicador <span class="required">*</span>
                          </label>
                          <div class="col-md-4 col-sm-6 col-xs-12">                                           
                          
                          	<select name="indicador_id" id="indicador_id"  required="required"  class="form-control col-md-7 col-xs-12">
                          	<?php 
                          		foreach($indicadores as $indicador)
                          		{
                          			if($indicadorProjeto->indicador_id == $indicador->indicador_id){
                          				$selected = "selected";
                          			}else{
                          				$selected = "";
                          			}
                          	?>
                          	<h3><?php echo $indicadorProjeto->indicador_id.'-'.$indicador->indicador_id.'-'.$indicador->indicador_nome."<br>"; ?></h3>
                          	
                          		<option <?php echo $selected;?> value="<?php echo $indicador->indicador_id; ?>"><?php echo $indicador->indicador_nome; ?></option>
                          	<?php 
                          		}
                          	
                          	?>
                          	</select>
                          </div>
                        </div>                        
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_fase">Fase <span class="required">*</span>
                          </label>
                          <div class="col-md-3 col-sm-6 col-xs-12">
                          <?php 
	                          $iniciacao = "";
	                          $planejamento = "";
	                          $execucao = "";
	                          $monitoramento = "";
	                          $encerramento = "";
	                          
                          	if(utf8_decode($indicadorProjeto->projeto_fase) == "Iniciação"){
                          		$iniciacao = "selected";
                          	}else if(utf8_decode($indicadorProjeto->projeto_fase) == "Planejamento"){
                          		$planejamento = "selected";
                          	}else if(utf8_decode($indicadorProjeto->projeto_fase) == "Execução"){
                          		$execucao = "selected";
                          	}else if(utf8_decode($indicadorProjeto->projeto_fase) == "Monitoramento e Controle"){
                          		$monitoramento = "selected";
                          	}else if(utf8_decode($indicadorProjeto->projeto_fase) == "Encerramento"){
                          		$encerramento = "selected";
                          	}
                          
                          ?>                         
                          
                          	<select id="projeto_fase" name="projeto_fase" required="required"  class="form-control col-md-7 col-xs-12">
                          		<option <?php echo $iniciacao; ?> value="Iniciacao">Iniciação</option>
                          		<option <?php echo $planejamento; ?> value="Planejamento">Planejamento</option>
                          		<option <?php echo $execucao; ?> value="Execucao">Execução</option>
                          		<option <?php echo $monitoramento; ?> value="Monitoramento e Controle">Monitoramento e Controle</option>
                          		<option <?php echo $encerramento; ?> value="Encerramento">Encerramento</option>
                          	</select>
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="valor_minimo">Valor Mínimo <span class="required">*</span>
                          </label>
                          <div class="col-md-2 col-sm-6 col-xs-12">
                            <input type="number" id="valor_minimo" value="<?php echo $indicadorProjeto->valor_minimo; ?>" name="valor_minimo" required="required" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="valor_maximo">Valor Máximo <span class="required">*</span>
                          </label>
                          <div class="col-md-2 col-sm-6 col-xs-12">
                            <input type="number" id="valor_maximo" value="<?php echo $indicadorProjeto->valor_maximo; ?>" name="valor_maximo" required="required" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>


                        <div class="form-group"> 
                          	<label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                        
						    <div class="control-label col-sm-1">
						      <button type="submit" class="btn btn-default">Editar</button>
						    </div>
						    <div class="control-label col-sm-2">
						        <button type="reset" class="btn btn-default" onclick="location.href='<?php echo $this->url('indicador_projeto/consulta', array('action'=>'consulta', 'id' => $projeto_id));?>'">Cancelar</button>
						  </div>
					  </div>
					  					  
                  </div>
                  </form>
                  <!-- End SmartWizard Content -->

                </div>
              </div>
            </div>

          </div>
        </div>

        <!-- footer content -->
        <footer>
          <div class="copyright-info">
            <p class="pull-right">© 2016 Produzido por Laislla Costa Ramos
            </p>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
      <!-- /page content -->
