        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Indicadores </h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Novo Indicador <small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                   <li><a class="link"  href="<?php echo $this->url('indicador'); ?>" ><i class="fa fa-chevron-left" aria-hidden="true"></i> Voltar</a></li>
                     <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>                      
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content">


                  <!-- Smart Wizard -->
                  <p>Esse é o formulário onde deve ser preenchidas todas as informações do novo indicador.</p>
                  
  				<form method="post" action="<?php echo $this->url('indicador/add',  array('action'=>'add'));?>" role="form" class="form-horizontal form-label-left">
                                                
                    <div>

                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome">Título <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" id="indicador_nome" name="indicador_nome" required="required" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>

                    </div>
                    
                    
                        <div class="form-group"> 
                          	<label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                        
						    <div class="control-label col-sm-1">
						      <button type="submit" class="btn btn-default">Cadastrar</button>
						    </div>
						    <div class="control-label col-sm-2">
						       <button type="reset" class="btn btn-default" onclick="location.href='<?php echo $this->url('indicador', array('action'=>'index'));?>'">Cancelar</button>
						   </div>
					  </div>
                    
                  </form>
                  <!-- End SmartWizard Content -->

                </div>
              </div>
            </div>

          </div>
        </div>  