<?php

 $title = 'Excluir Indicador';
 $this->headTitle($title);
 ?>
        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Indicadores </h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12" style="text-align: center;">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Excluir Indicador - <?php echo $indicador->indicador_nome; ?><small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                   <li><a class="link"  href="<?php echo $this->url('indicador'); ?>" ><i class="fa fa-chevron-left" aria-hidden="true"></i> Voltar</a></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>                      
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content"> 
 
                  <!-- Smart Wizard -->
                  
				 <p>Tem certeza que deseja excluir <br>
				     <strong><?php echo $this->escapeHtml($indicador->indicador_nome); ?></strong>?
				 </p>
 
                  
  				<form action="<?php echo $this->url('indicador/delete', array('action' => 'delete','id' => $this->id)); ?>" method="post" role="form" class="form-horizontal form-label-left">
              
                  <div  style="text-align: center;">
                  
                                            
     
     						<input type="hidden" name="id" value="<?php echo (int) $indicador->indicador_id; ?>" />
     								
							  <div class="form-group"> 
							    <div class="control-label col-md-6 col-sm-6 col-xs-6">
							      <button type="submit" class="btn btn-default" name="submit" value="Sim">Sim</button>
							    </div>
							    <div class="control-label col-md-1 col-sm-1 col-xs-1"">
							      <button type="submit" class="btn btn-default" name="submit" value="Nao">Não</button>
							    </div>
							  </div>
					  
                  </div>
                  </form>
                  <!-- End SmartWizard Content -->

                </div>
              </div>
            </div>

          </div>
        </div>