<?php

 $title = 'Visualizar Indicador';
 $this->headTitle($title);
 ?>
         <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Indicadores </h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12" style="text-align: center;">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Indicador Detalhe - <?php echo $indicador->indicador_nome; ?> <small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="link"  href="<?php echo $this->url('indicador'); ?>" ><i class="fa fa-chevron-left" aria-hidden="true"></i> Voltar</a></li>
                   <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>                      
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content"> 
 
                  <!-- Smart Wizard --> 
                  
  				<form action="" method="post" role="form" class="form-horizontal form-label-left">
                   						
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome">Título:
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome"><?php echo $indicador->indicador_nome; ?>
                          </label>      	
                          </div>
                        </div>	
                  
                  </form>
                  <!-- End SmartWizard Content -->

                </div>
              </div>
            </div>

          </div>
        </div>