       <!-- page content -->
      <div class="right_col" role="main">

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Indicadores </h3>
            </div>

            <div class="title_right">
              <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search for...">
                  <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Buscar!</button>
                        </span>
                </div>
              </div>
            </div>
          </div>
          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Consultar Indicadores</h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="link"  href="<?php echo $this->url('indicador/add'); ?>" ><i class="fa fa-plus" aria-hidden="true"></i> Adicionar</a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">

                  <p>Lista todos os indicadores</p>

                  <!-- start project list -->
                  <table class="table table-striped projects">
                    <thead>
                      <tr>
                        <th style="width: 1%">#</th>
                        <th style="width: 20%">Indicador</th>
                        <th style="width: 20%">Edição</th>
                      </tr>
                    </thead>
                    
                    <tbody>
                    <?php 

						foreach ($indicadores as $indicador)
						{
					?>
                      <tr>
                        <td><?php echo $indicador->indicador_id; ?></td>
                        <td>
                          <a><?php echo utf8_decode($indicador->indicador_nome); ?></a>
                        </td>
                        <td>
                          <a href="<?php echo $this->url('indicador/detalhe', array('id' => $indicador->indicador_id)); ?>" class="btn btn-info btn-xs"><i class="fa fa-folder"></i>  </a>
                          <a href="<?php echo $this->url('indicador/edit', array('id' => $indicador->indicador_id)); ?>" class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i>  </a>
                          <a href="<?php echo $this->url('indicador/delete', array('id' => $indicador->indicador_id)); ?>" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i>  </a>
                        </td>
                      </tr>
                      <?php 
						}
                      ?>                      
                    </tbody>
                  </table>
                  <!-- end project list -->

                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- footer content -->
        <footer>
          <div class="copyright-info">
            <p class="pull-right">© 2016 Produzido por Laislla Costa Ramos
            </p>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
      <!-- /page content -->

  <script src="<?php echo $this->basePath('js/bootstrap.min.js'); ?>"></script>

  <!-- chart js -->
  <script src="<?php echo $this->basePath('js/chartjs/chart.min.js'); ?>"></script>
  <!-- bootstrap progress js -->
  <script src="<?php echo $this->basePath('js/progressbar/bootstrap-progressbar.min.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/nicescroll/jquery.nicescroll.min.js'); ?>"></script>
  <!-- icheck -->
  <script src="<?php echo $this->basePath('js/icheck/icheck.min.js'); ?>"></script>

  <script src="<?php echo $this->basePath('js/custom.js'); ?>"></script>

  <!-- pace -->
  <script src="<?php echo $this->basePath('js/pace/pace.min.js'); ?>"></script>


