<?php 
     use Zend\Session\Container;  
	 $session_dados = new Container('usuario_dados');   
 ?>  
         <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Indicadores </h3>
            </div>
          </div>
          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Consultar Indicadores</h2>
                  <ul class="nav navbar-right panel_toolbox">
		              <?php if(in_array('indicador/add', $session_dados->funcionalidades_usuario)){ ?>
                    <li><a class="link"  href="<?php echo $this->url('indicador/add'); ?>" ><i class="fa fa-plus" aria-hidden="true"></i> Adicionar</a>
                    </li>
                    <?php }?>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content" class="table-responsive">

                  <p>Lista todos os indicadores</p>

                  <!-- start project list -->
                  <table id="minhatabela" class="table table-striped">
                    <thead>
                      <tr>
                        <th style="width: 1%">#</th>
                        <th style="width: 20%">Indicador</th>
                        <th style="width: 20%">Edi&ccedil;&atilde;o</th>
                      </tr>
                    </thead>
                    
                    <tbody>
                    <?php 

						foreach ($indicadores as $indicador)
						{
					?>
                      <tr>
                        <td><?php echo $indicador->indicador_id; ?></td>
                        <td>
                          <a><?php echo (utf8_decode($indicador->indicador_nome)); ?></a>
                        </td>
                        <td>
		              	<?php if(in_array('indicador/detalhe', $session_dados->funcionalidades_usuario)){ ?>
                          <a href="<?php echo $this->url('indicador/detalhe', array('id' => $indicador->indicador_id)); ?>" data-toggle="tooltip" data-placement="top" title="Ver Detalhado" class="btn btn-info btn-xs"><i class="fa fa-folder"></i>  </a>
                        <?php } ?>  
		              <?php if(in_array('indicador/edit', $session_dados->funcionalidades_usuario)){ ?>
                          <a href="<?php echo $this->url('indicador/edit', array('id' => $indicador->indicador_id)); ?>" data-toggle="tooltip" data-placement="top" title="Alterar" class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i>  </a>
                          <?php }?>                          
		              <?php if(in_array('indicador/delete', $session_dados->funcionalidades_usuario)){ ?>
                          <a href="<?php echo $this->url('indicador/delete', array('id' => $indicador->indicador_id)); ?>" data-toggle="tooltip" data-placement="top" title="Excluir" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i>  </a>
                        <?php }?>
                        </td>
                      </tr>
                      <?php 
						}
                      ?>                      
                    </tbody>
                  </table>
                  <!-- end project list -->

                </div>
              </div>
            </div>
          </div>
        </div>

  <script src="<?php echo $this->basePath('js/bootstrap.min.js'); ?>"></script>

  <!-- chart js -->
  <script src="<?php echo $this->basePath('js/chartjs/chart.min.js'); ?>"></script>
  <!-- bootstrap progress js -->
  <script src="<?php echo $this->basePath('js/progressbar/bootstrap-progressbar.min.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/nicescroll/jquery.nicescroll.min.js'); ?>"></script>
  <!-- icheck -->
  <script src="<?php echo $this->basePath('js/icheck/icheck.min.js'); ?>"></script>

  <script src="<?php echo $this->basePath('js/custom.js'); ?>"></script>

  <script src="<?php echo $this->basePath('js/jquery.dataTables.min.js'); ?>"></script>

  <!-- pace -->
  <script src="<?php echo $this->basePath('js/pace/pace.min.js'); ?>"></script>
  
		    <script>
			    $(document).ready(function(){
			        $('#minhatabela').dataTable();
			    });
		        
		    </script>

