      <script>
	
	function validateForm(){
    	var segundos = 5;
    	
	    var pass_anterior = document.getElementById('usuario_senha_anterior').value;
	    var pass_atual = document.getElementById('usuario_senha_atual').value;
	    var pass_nova = document.getElementById('usuario_senha').value;
	    var pass_nova_confirma = document.getElementById('usuario_senha_confirma').value;
		var tam_senha = pass_nova.length;
	    
	    if(pass_anterior !=  pass_atual){	
	    	
	    	document.getElementById('alerta').innerHTML = "A senha digitada não confere com a senha atual.";
	        document.getElementById('alerta').style.display = 'block';
	    		  	    	
	    	setTimeout(function(){
	    	  $('#alerta').fadeOut();
	    	}, segundos*1000);  
	    	   
	        return false;		
	    }
	    
	    if(tam_senha < 6){
		    
	    	document.getElementById('alerta').innerHTML = "A senha deve ter no minimo 6 digitos!";
	        document.getElementById('alerta').style.display = 'block';
	    		  	    	
	    	setTimeout(function(){
	    	  $('#alerta').fadeOut();
	    	}, segundos*1000);  
	    	   
	        return false;	
		}

	    if(pass_nova == ""  || pass_nova_confirma == ""){ 
		    
	    	document.getElementById('alerta').innerHTML = "A nova senha e a confirmação de nova senha devem ser iguais!";
	        document.getElementById('alerta').style.display = 'block';
	    		  	    	
	    	setTimeout(function(){
	    	  $('#alerta').fadeOut();
	    	}, segundos*1000);  
	    	   
	        return false;	 
	    }
	    
		if(pass_nova != pass_nova_confirma){
		    
	    	document.getElementById('alerta').innerHTML = "A nova senha e a confirmação de nova senha devem ser iguais!";
	        document.getElementById('alerta').style.display = 'block';
	    		  	    	
	    	setTimeout(function(){
	    	  $('#alerta').fadeOut();
	    	}, segundos*1000);  
	    	   
	        return false;	 
	    }else{	    
	        $('#edit-senha').submit(); 
	        return true;
	    }
	}
	
	function mostrarMensagemErro(msg){	    
		     
	}

	

    </script>
    
      <!-- page content -->
      <div class="right_col" role="main">

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Usuários</h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Alterar Senha do Usuário <?php echo $usuario->usuario_nome; ?><small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"></a>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>                      
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content">


                  <!-- Smart Wizard -->
                  <p>Esse é o formulário onde deve ser preenchidas todas as informações da nova senha de usuário.</p> <br>
                                       
  				<form id="edit-senha" name="edit-senha"  onSubmit="validateForm(); return false;" method="post" action="<?php echo $this->url('usuario/edit',  array('action'=>'editSenha', 'id' => $usuario->usuario_id));?>" role="form" class="form-horizontal form-label-left" enctype="multipart/form-data">
              		<input type="hidden" name="usuario_senha_anterior" id="usuario_senha_anterior" value="<?php echo $usuario->usuario_senha; ?>">
              		<input type="hidden" name="usuario_nome" id="usuario_nome" value="<?php echo $usuario->usuario_nome; ?>">
              		<input type="hidden" name="usuario_email" id="usuario_email" value="<?php echo $usuario->usuario_email; ?>">
              		<input type="hidden" name="perfil_id" id="perfil_id" value="<?php echo $usuario->perfil_id; ?>">
                  <div>   
                  		<div class="alert alert-danger" id="alerta" name="alerta" style="display: none;">
						  <strong>Erro!</strong> 
						</div>        
                        <div class="form-group">
                          <label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12">Senha atual <span class="required">*</span></label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                            <input id="usuario_senha_atual" class="form-control col-md-7 col-xs-12" type="password" name="usuario_senha_atual">
                          </div>
                        </div>    
                                  
                        <div class="form-group">
                          <label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12">Nova senha <span class="required">*</span></label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                            <input id="usuario_senha" class="form-control col-md-7 col-xs-12" type="password" name="usuario_senha">
                          </div>
                        </div> 
                                     
                        <div class="form-group">
                          <label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12">Confirmar nova senha <span class="required">*</span></label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                            <input id="usuario_senha_confirma" class="form-control col-md-7 col-xs-12" type="password" name="usuario_senha_confirma">
                          </div>
                        </div>
                           
                        <div class="form-group"> 
                          	<label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                        
						    <div class="control-label col-sm-1">
						      <button type="submit" class="btn btn-default">Alterar</button>
						    </div>
						    <div class="control-label col-sm-2">
						      <button type="reset" class="btn btn-default" onclick="location.href='<?php echo $this->url('home', array('action'=>'index'));?>'">Cancelar</button>
						    </div>
					  </div>
					  
                  </div>
                  </form>

                </div>
              </div>
            </div>

          </div>
        </div>

        <!-- footer content -->
        <footer>
          <div class="copyright-info">
            <p class="pull-right">© 2016 Produzido por Laislla Costa Ramos
            </p>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
      <!-- /page content -->
