 <script>
	
	function validateForm(){
    	var segundos = 5;
		
		var senha = document.getElementById("usuario_senha").value;
	    
	    if (senha.length < 6 ) {
		    
	    	document.getElementById('alerta').innerHTML = "A Senha deve conter no mínimo 6 dígitos!";
	        document.getElementById('alerta').style.display = 'block';
	    		  	    	
	    	setTimeout(function(){
	    	  $('#alerta').fadeOut();
	    	}, segundos*1000);  
	    	   
	        return false;		        
	    } else {
		       $('#usuario_edit').submit(); 
		       return true;
	    }		
	}

</script>

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Usu&aacute;rios</h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Editar Usu&aacute;rio <?php echo utf8_decode($usuario->usuario_nome); ?><small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="link"  href="<?php echo $this->url('usuario'); ?>" ><i class="fa fa-chevron-left" aria-hidden="true"></i> Voltar</a></li>
                   
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>                      
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content">


                  <!-- Smart Wizard -->
                  <p>Esse &eacute; o formul&aacute;rio onde deve ser preenchidas todas as informa&ccedil;&otilde;es do usu&aacute;rio.</p> <br>
                  
  				<form id="usuario_edit" name="usuario_edit"  onSubmit="validateForm(); return false;"   method="post" action="<?php echo $this->url('usuario/edit',  array('action'=>'edit', 'id' => $usuario->usuario_id));?>" role="form" class="form-horizontal form-label-left">
              
                  <div>
                  		<div class="alert alert-danger" id="alerta" name="alerta" style="display: none;">
						  <strong>Erro!</strong> 
						</div>
						
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="usuario_nome">Nome <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" id="usuario_nome" name="usuario_nome" required="required" value="<?php echo utf8_decode($usuario->usuario_nome); ?>" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="usuario_email">E-mail <span class="required">*</span>
                          </label>
                          <div class="col-md-5 col-sm-5 col-xs-12">
                            <input type="email" id="usuario_email" name="usuario_email" required="required"  value="<?php echo $usuario->usuario_email; ?>" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12">Senha <span class="required">*</span></label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                            <input id="usuario_senha" class="form-control col-md-7 col-xs-12" required="required"  value="<?php echo $usuario->usuario_senha; ?>" type="password" name="usuario_senha">
                          </div>
                        </div>
                                                
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="perfil_id">Perfil <span class="required">*</span>
                          </label>
                          <div class="col-md-3 col-sm-6 col-xs-12">
                          	<select name="perfil_id" id="perfil_id"  required="required"  class="form-control col-md-7 col-xs-12">
                          	<?php 
                          			foreach($perfis as $perfil){
                          				if($perfil->perfil_id == $usuario->perfil_id){
                          	?>
                          			
                          		<option selected value="<?php echo $perfil->perfil_id; ?>"><?php echo utf8_decode($perfil->perfil_nome); ?></option>
                          	<?php 
                          				}else{ ?>
                          				
                          		<option value="<?php echo $perfil->perfil_id; ?>"><?php echo utf8_decode($perfil->perfil_nome); ?></option>
                          				
                          	<?php 
                          				}
                          			}
                          	?>
                          	</select>
                          </div>
                        </div>   
                           
                        <div class="form-group"> 
                          	<label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                        
						    <div class="control-label col-sm-1">
						      <button type="submit" class="btn btn-default">Editar</button>
						    </div>
						    <div class="control-label col-sm-2">
						      <button type="reset" class="btn btn-default" onclick="location.href='<?php echo $this->url('usuario', array('action'=>'index'));?>'">Cancelar</button>
						    </div>
					  </div>
					  
                  </div>
                  </form>

                </div>
              </div>
            </div>

          </div>
        </div>