       <!-- page content -->
      <div class="right_col" role="main">

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Usuários </h3>
            </div>

            <div class="title_right">
              <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search for...">
                  <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Buscar!</button>
                        </span>
                </div>
              </div>
            </div>
          </div>
          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Consulta Usuários</h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="link"  href="<?php echo $this->url('usuario/add'); ?>" ><i class="fa fa-plus" aria-hidden="true"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">

                  <p>Lista de todos os usuários</p>

                  <!-- start project list -->
                  <table class="table table-striped projects">
                    <thead>
                      <tr>
                        <th style="width: 1%">#</th>
                        <th style="width: 20%">Nome</th>
                        <th>E-mail</th>
                        <th>Perfil</th>
                        <th style="width: 20%">Edição</th>
                      </tr>
                    </thead>
                    
                    <tbody>
                    <?php 

                    $array_perfis = Array();
                    
                    foreach ($perfis as $perfil){
                    	$array_perfis[$perfil->perfil_id] = $perfil->perfil_nome;                    	
                    }
                    
						foreach ($usuarios as $usuario)
						{
					?>
                      <tr>
                        <td><?php echo $usuario->usuario_id; ?></td>
                        <td><?php echo $usuario->usuario_nome; ?></td>
                        <td><?php echo $usuario->usuario_email; ?></td>
                        <td><?php echo utf8_decode($array_perfis[$usuario->perfil_id]); ?>
                        
                        </td>
                        
                        <td>
                          <a href="<?php echo $this->url('usuario/detalhe', array('id' => $usuario->usuario_id)); ?>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i>  </a>
                          <a href="<?php echo $this->url('usuario/edit', array('id' => $usuario->usuario_id)); ?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i>  </a>
                          <a href="<?php echo $this->url('usuario/delete', array('id' => $usuario->usuario_id)); ?>" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i>  </a>
                        </td>
                      </tr>
                      <?php 
						}
                      ?>                      
                    </tbody>
                  </table>
                  <!-- end project list -->

                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- footer content -->
        <footer>
          <div class="copyright-info">
            <p class="pull-right">© 2016 Produzido por Laislla Costa Ramos
            </p>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
      <!-- /page content -->

  <script src="<?php echo $this->basePath('js/bootstrap.min.js'); ?>"></script>

  <!-- chart js -->
  <script src="<?php echo $this->basePath('js/chartjs/chart.min.js'); ?>"></script>
  <!-- bootstrap progress js -->
  <script src="<?php echo $this->basePath('js/progressbar/bootstrap-progressbar.min.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/nicescroll/jquery.nicescroll.min.js'); ?>"></script>
  <!-- icheck -->
  <script src="<?php echo $this->basePath('js/icheck/icheck.min.js'); ?>"></script>

  <script src="<?php echo $this->basePath('js/custom.js'); ?>"></script>

  <!-- pace -->
  <script src="<?php echo $this->basePath('js/pace/pace.min.js'); ?>"></script>


