 <?php 
use Zend\Session\Container;
$session_dados = new Container('usuario_dados');
?> 
        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Usu&aacute;rios </h3>
            </div>
          </div>
          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Consultar Usu&aacute;rios</h2>
                  <ul class="nav navbar-right panel_toolbox">
                  
                  	<?php if(in_array('usuario/add', $session_dados->funcionalidades_usuario)){  ?>
                    <li><a class="link"  href="<?php echo $this->url('usuario/add'); ?>" ><i class="fa fa-plus" aria-hidden="true"></i> Adicionar</a>
                    </li>
                    <?php } ?>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content" class="table-responsive">

                  <p>Lista todos os usu&aacute;rios</p>

                  <!-- start project list -->
                  <table id="minhatabela" class="table table-striped">
                    <thead>
                      <tr>
                        <th style="width: 1%">#</th>
                        <th style="width: 20%">Nome</th>
                        <th>E-mail</th>
                        <th>Perfil</th>
                        <th style="width: 20%">Edi&ccedil;&atilde;o</th>
                      </tr>
                    </thead>
                    
                    <tbody>
                    <?php 

                    $array_perfis = Array();
                    
                    foreach ($perfis as $perfil){
                    	$array_perfis[$perfil->perfil_id] = utf8_decode($perfil->perfil_nome);                    	
                    }
                    
						foreach ($usuarios as $usuario)
						{
					?>
                      <tr>
                        <td><?php echo $usuario->usuario_id; ?></td>
                        <td><?php echo utf8_decode($usuario->usuario_nome); ?></td>
                        <td><?php echo $usuario->usuario_email; ?></td>
                        <td><?php echo ($array_perfis[$usuario->perfil_id]); ?></td>
                        
                        <td>
                  		<?php if(in_array('usuario/detalhe', $session_dados->funcionalidades_usuario)){  ?>
                          <a href="<?php echo $this->url('usuario/detalhe', array('id' => $usuario->usuario_id)); ?>" data-toggle="tooltip" data-placement="top" title="Ver Detalhado" class="btn btn-info btn-xs"><i class="fa fa-folder"></i>  </a>
                        <?php }?>
                  		<?php if(in_array('usuario/edit', $session_dados->funcionalidades_usuario)){  ?>
                          <a href="<?php echo $this->url('usuario/edit', array('id' => $usuario->usuario_id)); ?>" data-toggle="tooltip" data-placement="top" title="Alterar" class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i>  </a>
                        <?php }?>
                  		<?php if(in_array('usuario/delete', $session_dados->funcionalidades_usuario)){  ?>
                          <a href="<?php echo $this->url('usuario/delete', array('id' => $usuario->usuario_id)); ?>" data-toggle="tooltip" data-placement="top" title="Excluir" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i>  </a>
                        <?php }?>
                        </td>
                        
                      </tr>
                      <?php 
						}
                      ?>                      
                    </tbody>
                  </table>
                  <!-- end project list -->

                </div>
              </div>
            </div>
          </div>
        </div>

  <script src="<?php echo $this->basePath('js/bootstrap.min.js'); ?>"></script>

  <!-- chart js -->
  <script src="<?php echo $this->basePath('js/chartjs/chart.min.js'); ?>"></script>
  <!-- bootstrap progress js -->
  <script src="<?php echo $this->basePath('js/progressbar/bootstrap-progressbar.min.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/nicescroll/jquery.nicescroll.min.js'); ?>"></script>
  <!-- icheck -->
  <script src="<?php echo $this->basePath('js/icheck/icheck.min.js'); ?>"></script>

  <script src="<?php echo $this->basePath('js/custom.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/jquery.dataTables.min.js'); ?>"></script>

  <!-- pace -->
  <script src="<?php echo $this->basePath('js/pace/pace.min.js'); ?>"></script>
  
		    <script>
			    $(document).ready(function(){
			        $('#minhatabela').dataTable();
			    });
		        
		    </script>
  



