   <script>
	
	function validateForm(){
    	var segundos = 5;

    		  var rads = document.getElementsByName("membros");
    		  var novo_membro = document.getElementById("usuario_id").value;

    		  var cont = 0;
    		  for(var i = 0; i < rads.length; i++){
        		  var membro = rads[i].value;
        		  if(novo_membro == membro){
        		    	document.getElementById('alerta').innerHTML = "Esse usuário já faz parte do projeto!";
        		        document.getElementById('alerta').style.display = 'block';
        		    		  	    	
        		    	setTimeout(function(){
        		    	  $('#alerta').fadeOut();
        		    	}, segundos*1000);  

        		    	cont = cont +1;
        		        return false;		        
        		  }
    		   }

		       $('#membro_add').submit(); 
		       return true;
	}

</script>   
     
      <!-- page content -->
      <div class="right_col" role="main">

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Membros do Projeto - <?php echo $projeto->projeto_nome; ?></h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Novo Membro de <?php echo $projeto->projeto_nome;?> <small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="link"  href="<?php echo $this->url('membro_projeto/consulta', array('id' => $id)); ?>" ><i class="fa fa-chevron-left" aria-hidden="true"></i> Voltar</a></li>
                   </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content">


                  <!-- Smart Wizard -->
                  <p>Esse é o formulário onde deve ser preenchidas todas as informações do novo membro.</p>
                  
  				<form id="membro_add" name="membro_add"  onSubmit="validateForm(); return false;"  method="post" action="<?php echo $this->url('membro_projeto/add', array('id' => $id));?>" role="form" class="form-horizontal form-label-left">
              
                          		<?php 
                          		foreach ($membros as $membro){
                          		?>
                          		
                          		<input type="hidden" id="membro_<?php echo $membro->usuario_id?>" name="membros" value="<?php echo $membro->usuario_id?>">
                          		
                          		<?php 
                          		}
                          		
                          		?>
              	
                  <div>        
                  		<div class="alert alert-danger" id="alerta" name="alerta" style="display: none;">
						  <strong>Erro!</strong> 
						</div>   	
                                                
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="usuario_id">Usuário <span class="required">*</span>
                          </label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                          	<select name="usuario_id" id="usuario_id"  required="required"  class="form-control col-md-7 col-xs-12">
                          	
                          		<?php 
                          		foreach ($usuarios as $usuario){
                          		?>
                          		
                          		<option value="<?php echo $usuario->usuario_id?>"><?php echo $usuario->usuario_nome; ?></option>
                          		
                          		<?php 
                          		}
                          		
                          		?>
                          	</select>
                          </div>
                        </div>	
                                                
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="projeto_membro_papel">Papel <span class="required">*</span>
                          </label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                          	<select name="projeto_membro_papel" id="projeto_membro_papel"  required="required"  class="form-control col-md-7 col-xs-12">
                          		<option value="Desenvolvedor">Desenvolvedor</option>
                          		<option value="Designer">Designer</option>
                          		<option value="Testador">Testador</option>
                          		<option value="Analista de Requisitos">Analista de Requisitos</option>
                          		<option value="Analista de negocio">Analista de negocio</option>
                          		<option value="Administrador de BD">Administrador de BD</option>
                          		<option value="Arquiteto da Informacao">Arquiteto da Informacao</option>
                          		<option value="Analista de Sistemas">Analista de Sistemas</option>
                          	</select>
                          </div>
                        </div>	
					  
                        <div class="form-group"> 
                          	<label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                        
						    <div class="control-label col-sm-1">
						      <button type="submit" class="btn btn-default">Cadastrar</button>
						    </div>
						    <div class="control-label col-sm-2">
						       <button type="reset" class="btn btn-default" onclick="location.href='<?php echo $this->url('membro_projeto/consulta', array('action'=>'consulta', 'id' => $id));?>'">Cancelar</button>
						     </div>
					  </div>
					  
                  </div>
                  </form>
                  <!-- End SmartWizard Content -->

                </div>
              </div>
            </div>

          </div>
        </div>

        <!-- footer content -->
        <footer>
          <div class="copyright-info">
            <p class="pull-right">© 2016 Produzido por Laislla Costa Ramos
            </p>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
      <!-- /page content -->
