<?php

 $title = 'Visualizar Membro do Projeto';
 $this->headTitle($title);
 ?>
 
       <!-- page content -->
      <div class="right_col" role="main">

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Membros do Projeto</h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12" style="text-align: center;">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2><?php echo $title;?> <small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"></a>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>                      
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content"> 
 
                  <!-- Smart Wizard --> 
                  
  				<form action="" method="post" role="form" class="form-horizontal form-label-left">
  				
  				<?php 
				 
				 $array_usuarios = Array();
				 
				 foreach($usuarios as $usuario){
				 	$array_usuarios[$usuario->usuario_id] = $usuario->usuario_nome;
				 }
				 ?>
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome">Membro:
                          </label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">
                          <label class="control-label "><?php echo $array_usuarios[$membro->usuario_id]; ?>
                          </label>      	
                          </div>
                        </div>		
                        	
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="indicador_nome">Papel: </label>
                          <div class="col-md-9 col-sm-9 col-xs-12" style="text-align: left;">                          
                          	<label class="control-label">Gerente</label>  
                          </div>
                        </div>	
                  
                  </form>
                  <!-- End SmartWizard Content -->

                </div>
              </div>
            </div>

          </div>
        </div>

        <!-- footer content -->
        <footer>
          <div class="copyright-info">
            <p class="pull-right">© 2016 Produzido por Laislla Costa Ramos
            </p>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
      <!-- /page content -->
                  
 
