      <!-- page content -->
      <div class="right_col" role="main">

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Usuário</h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Novo Usuário <small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"></a>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>                      
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content">


                  <!-- Smart Wizard -->
                  <p>Esse é o formulário onde deve ser preenchidas todas as informações do novo usuário.</p> <br>
                  
  				<form method="post" action="<?php echo $this->url('usuario/add',  array('action'=>'add'));?>" role="form" class="form-horizontal form-label-left">
              
                  <div>
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="usuario_nome">Nome <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" id="usuario_nome" name="usuario_nome" required="required" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="usuario_email">E-mail <span class="required">*</span>
                          </label>
                          <div class="col-md-5 col-sm-5 col-xs-12">
                            <input type="email" id="usuario_email" name="usuario_email" required="required" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12">Senha <span class="required">*</span></label>
                          <div class="col-md-3 col-sm-3 col-xs-12">
                            <input id="usuario_senha" class="form-control col-md-7 col-xs-12" type="password" name="usuario_senha">
                          </div>
                        </div>
                                                
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="perfil_id">Perfil <span class="required">*</span>
                          </label>
                          <div class="col-md-3 col-sm-6 col-xs-12">
                          	<select name="perfil_id" id="perfil_id"  required="required"  class="form-control col-md-7 col-xs-12">
                          	<?php 
                          			foreach($perfis as $perfil){
                          	?>
                          	
                          		<option value="<?php echo $perfil->perfil_id; ?>"><?php echo $perfil->perfil_nome?></option>
                          	<?php 
                          			}
                          	?>
                          	</select>
                          </div>
                        </div>   
                           
                        <div class="form-group"> 
                          	<label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                        
						    <div class="control-label col-sm-1">
						      <button type="submit" class="btn btn-default">Cadastrar</button>
						    </div>
						    <div class="control-label col-sm-2">
						      <button type="reset" class="btn btn-default" onclick="location.href='<?php echo $this->url('usuario', array('action'=>'index'));?>'">Cancelar</button>
						    </div>
					  </div>
					  
                  </div>
                  </form>

                </div>
              </div>
            </div>

          </div>
        </div>

        <!-- footer content -->
        <footer>
          <div class="copyright-info">
            <p class="pull-right">© 2016 Produzido por Laislla Costa Ramos
            </p>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
      <!-- /page content -->
