      <!-- page content -->
      <div class="right_col" role="main">

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Usuário</h3>
            </div>
            
          </div>
          <div class="clearfix"></div>

          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Editar Usuário <small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"></a>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>                      
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                
          <div class="row">
            <div class="col-md-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Perfis de Acesso X Funcionalidades</h2>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content" >

                  <p>Informe a funcionalidade que cada perfil terá acesso.</p>

                  <!-- Projetoo -->
                  <div class="row">

                    <div class="col-md-12">

                      <!-- price element -->
                      <div class="col-md-5 col-sm-6 col-xs-12">
                        <div class="pricing">
                          <div class="title">
				                          <label>
				                            <input type="checkbox"> <h1>Projetos</h1>
				                          </label>
                          </div>
                          
                          <div class="x_content">
                            <div class="">
                              <div class="pricing_features"  style="height: 400px;">
                                <ul class="list-unstyled text-left">
                                
                                  <li>
			                      	<div class="col-md-9 col-sm-9 col-xs-12">
	                                  <div class="checkbox">
				                          <label>
				                            <input type="checkbox" class="flat"> Cadastrar
				                          </label>
			                        	</div>
			                        </div>
                                   </li>
                                  <li>
			                      	<div class="col-md-9 col-sm-9 col-xs-12">
	                                  <div class="checkbox">
				                          <label>
				                            <input type="checkbox" class="flat"> Editar
				                          </label>
			                        	</div>
			                        </div>
                                   </li>
                                  <li>
			                      	<div class="col-md-9 col-sm-9 col-xs-12">
	                                  <div class="checkbox">
				                          <label>
				                            <input type="checkbox" class="flat"> Excluir
				                          </label>
			                        	</div>
			                        </div>
                                   </li>
                                   
                                  <li>
			                      	<div class="col-md-9 col-sm-9 col-xs-12">
	                                  <div class="checkbox">
				                          <label>
				                            <input type="checkbox" class="flat"> Visualizar
				                          </label>
			                        	</div>
			                        </div>
                                   </li>
                                   
                                  <li>
			                      	<div class="col-md-9 col-sm-9 col-xs-12">
	                                  <div class="checkbox">
				                          <label>
				                            <input type="checkbox" class="flat"> Membros do Projeto
				                          </label>
			                        	</div>
			                        </div>
                                   </li>
                                                                      
                                  <li>
			                      	<div class="col-md-9 col-sm-9 col-xs-12">
	                                  <div class="checkbox">
				                          <label>
				                            <input type="checkbox" class="flat"> Indicadores do Projeto
				                          </label>
			                        	</div>
			                        </div>
                                   </li>                                   
                                   
                                  <li>
			                      	<div class="col-md-9 col-sm-9 col-xs-12">
	                                  <div class="checkbox">
				                          <label>
				                            <input type="checkbox" class="flat"> Acompanhamento do Projeto
				                          </label>
			                        	</div>
			                        </div>
                                   </li>                                   
                                   
                                  <li>
			                      	<div class="col-md-9 col-sm-9 col-xs-12">
	                                  <div class="checkbox">
				                          <label>
				                            <input type="checkbox" class="flat"> Tarefas do Projeto
				                          </label>
			                        	</div>
			                        </div>
                                   </li>
                                   
                                </ul>
                              </div>
                            </div>
                            
                            <div class="pricing_footer">
                              <p>
                                <a href="javascript:void(0);">Marcar todos</a>
                              </p>
                              <p>
                                <a href="javascript:void(0);">Desmarcar todos</a>
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                      
                    </div>

                  </div>
                  
                  <!-- Projetoo -->
                  
                  <br>
                  
                  <!-- Projetoo -->
                  <div class="row">

                    <div class="col-md-12">

                      <!-- price element -->
                      <div class="col-md-5 col-sm-6 col-xs-12">
                        <div class="pricing">
                          <div class="title">
				                          <label>
				                            <input type="checkbox"> <h1>Indicadores</h1>
				                          </label>
                          </div>
                          
                          <div class="x_content">
                            <div class="">
                              <div class="pricing_features"  style="height: 200px;">
                                <ul class="list-unstyled text-left">
                                
                                  <li>
			                      	<div class="col-md-9 col-sm-9 col-xs-12">
	                                  <div class="checkbox">
				                          <label>
				                            <input type="checkbox" class="flat"> Cadastrar
				                          </label>
			                        	</div>
			                        </div>
                                   </li>
                                  <li>
			                      	<div class="col-md-9 col-sm-9 col-xs-12">
	                                  <div class="checkbox">
				                          <label>
				                            <input type="checkbox" class="flat"> Editar
				                          </label>
			                        	</div>
			                        </div>
                                   </li>
                                  <li>
			                      	<div class="col-md-9 col-sm-9 col-xs-12">
	                                  <div class="checkbox">
				                          <label>
				                            <input type="checkbox" class="flat"> Excluir
				                          </label>
			                        	</div>
			                        </div>
                                   </li>
                                   
                                  <li>
			                      	<div class="col-md-9 col-sm-9 col-xs-12">
	                                  <div class="checkbox">
				                          <label>
				                            <input type="checkbox" class="flat"> Visualizar
				                          </label>
			                        	</div>
			                        </div>
                                   </li>
                                   
                                </ul>
                              </div>
                            </div>
                            
                            <div class="pricing_footer">
                              <p>
                                <a href="javascript:void(0);">Marcar todos</a>
                              </p>
                              <p>
                                <a href="javascript:void(0);">Desmarcar todos</a>
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                      
                    </div>

                  </div>
                  
                  <!-- Projetoo -->
                  
                  
                  <br>
                  <!-- Projetoo -->
                  <div class="row">

                    <div class="col-md-12">

                      <!-- price element -->
                      <div class="col-md-5 col-sm-6 col-xs-12">
                        <div class="pricing">
                          <div class="title">
				                          <label>
				                            <input type="checkbox"> <h1>Usuários</h1>
				                          </label>
                          </div>
                          
                          <div class="x_content">
                            <div class="">
                              <div class="pricing_features"  style="height: 200px;">
                                <ul class="list-unstyled text-left">
                                
                                  <li>
			                      	<div class="col-md-9 col-sm-9 col-xs-12">
	                                  <div class="checkbox">
				                          <label>
				                            <input type="checkbox" class="flat"> Cadastrar
				                          </label>
			                        	</div>
			                        </div>
                                   </li>
                                  <li>
			                      	<div class="col-md-9 col-sm-9 col-xs-12">
	                                  <div class="checkbox">
				                          <label>
				                            <input type="checkbox" class="flat"> Editar
				                          </label>
			                        	</div>
			                        </div>
                                   </li>
                                  <li>
			                      	<div class="col-md-9 col-sm-9 col-xs-12">
	                                  <div class="checkbox">
				                          <label>
				                            <input type="checkbox" class="flat"> Excluir
				                          </label>
			                        	</div>
			                        </div>
                                   </li>
                                   
                                  <li>
			                      	<div class="col-md-9 col-sm-9 col-xs-12">
	                                  <div class="checkbox">
				                          <label>
				                            <input type="checkbox" class="flat"> Visualizar
				                          </label>
			                        	</div>
			                        </div>
                                   </li>                                  
                                   
                                </ul>
                              </div>
                            </div>
                            
                            <div class="pricing_footer">
                              <p>
                                <a href="javascript:void(0);">Marcar todos</a>
                              </p>
                              <p>
                                <a href="javascript:void(0);">Desmarcar todos</a>
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                      
                    </div>

                  </div>
                  
                  <!-- Projetoo -->
                  
                  <br>
                  <!-- Projetoo -->
                  <div class="row">

                    <div class="col-md-12">

                      <!-- price element -->
                      <div class="col-md-5 col-sm-6 col-xs-12">
                        <div class="pricing">
                          <div class="title">
                            
				                          <label>
				                            <input type="checkbox"> <h1>Perfil de Acesso</h1>
				                          </label>
                          </div>
                               
                                             
                        </div>
                      </div>
                      
                    </div>

                  </div>
                  <br>
                  
                  <div class="row">

                    <div class="col-md-12">

                      <!-- price element -->
                      <div class="col-md-5 col-sm-6 col-xs-12">
                        <div class="pricing">
                          <div class="title">
				                          <label>
				                            <input type="checkbox"> <h1>Relatórios</h1>
				                          </label>
                          </div>
                                                    
                        </div>
                      </div>
                      
                    </div>

                  </div>
                  
                  <!-- Projetoo -->
                  
                </div>
              </div>
            </div>
          </div>
              </div>
            </div>

          </div>
        </div>

        <!-- footer content -->
        <footer>
          <div class="copyright-info">
            <p class="pull-right">© 2016 Produzido por Laislla Costa Ramos
            </p>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
      <!-- /page content -->
