       <!-- page content -->
      <div class="right_col" role="main">

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Perfil de Acesso </h3>
            </div>
            
          </div>
          <div class="clearfix"></div>
    
                  
  				<form method="post" action="<?php echo $this->url('perfil-acesso/add',  array('action'=>'add'));?>" role="form" class="form-horizontal form-label-left">
                   
                  <input type="hidden" name="perfil_id" id="perfil_id" value="1">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Administrador <small>Marque todas as funcionalidades que esse perfil terá acesso.<br></small></h2>
                  
                  <div class="clearfix"></div>
                </div>

                <div class="x_content">

                  <table class="table table-striped responsive-utilities jambo_table bulk_action">
                    <thead>
                      <tr class="headings">
                        <th>
                          <input type="checkbox" value="" name="funcionalidades[]" id="funcionalidades" class="flat">
                        </th>
                        <th class="column-title" colspan="6">Projetos </th>
                      </tr>
                    </thead>

                    <tbody>
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input type="checkbox" value="1" <?php if(in_array('1', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Consultar
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="2" <?php if(in_array('2', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Cadastrar
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="3" <?php if(in_array('3', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Editar
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="5" <?php if(in_array('5', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Remover
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="4" <?php if(in_array('4', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Visualizar
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="22" <?php if(in_array('22', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Status
                         </td>
                      </tr>
                      
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input type="checkbox" value="7"  <?php if(in_array('7', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>" name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Consultar Indicadores
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="25"  <?php if(in_array('25', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>" name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Cadastrar Indicadores
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="26"  <?php if(in_array('26', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>" name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Editar Indicadores
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="27"  <?php if(in_array('27', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>" name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Remover Indicadores
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="39"  <?php if(in_array('39', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>" name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Visualizar Indicadores
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="28"  <?php if(in_array('28', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>" name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Analisar Indicadores
                         </td>
                      </tr>
                      
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input type="checkbox" value="9" <?php if(in_array('9', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Consultar Tarefas
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="36" <?php if(in_array('36', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Cadastrar Tarefas
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="37" <?php if(in_array('37', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Editar Tarefas
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="38" <?php if(in_array('38', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Remover Tarefas
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="35" <?php if(in_array('35', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Visualizar Tarefas
                         </td>
                         
                        <td class=" "></td>
                      </tr>
                      
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input type="checkbox" value="6" <?php if(in_array('6', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Consultar Membros
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="29" <?php if(in_array('29', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Cadastrar Membros
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="31" <?php if(in_array('31', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Editar Membros
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="32" <?php if(in_array('32', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Remover Membros
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="30" <?php if(in_array('30', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Visualizar Membros
                         </td>
                         
                        <td class=" "></td>
                        
                        
                      </tr>
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input type="checkbox" value="8" "<?php if(in_array('8', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Consultar Acompanhamentos
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="33" <?php if(in_array('33', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Visualizar Acompanhamentos
                         </td>
                        <td class=" ">
                          <input type="checkbox" value="34" <?php if(in_array('34', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  name="funcionalidades[]" id="funcionalidades"  class="flat">
                          Editar Acompanhamentos
                         </td>
                         
                        <td class=" "></td>
                        
                        <td class=" "></td>
                        
                        <td class=" "></td>
                      </tr>
                     
                    </tbody>

                  </table>
                  
                  <table class="table table-striped responsive-utilities jambo_table bulk_action">
                    <thead>
                      <tr class="headings">
                        <th>
                          <input type="checkbox" id="check-all" class="flat">
                        </th>
                        <th class="column-title" colspan="6">Indicadores </th>
                      </tr>
                    </thead>

                    <tbody>
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input type="checkbox" <?php if(in_array('10', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  value="10" name="funcionalidades[]" id="funcionalidades" class="flat">
                          Consultar
                         </td>
                        <td class=" ">
                          <input type="checkbox"  <?php if(in_array('11', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  value="11" name="funcionalidades[]" id="funcionalidades" class="flat">
                          Cadastrar
                         </td>
                        <td class=" ">
                          <input type="checkbox"  <?php if(in_array('12', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  value="12" name="funcionalidades[]" id="funcionalidades" class="flat">
                          Editar
                         </td>
                        <td class=" ">
                          <input type="checkbox" <?php if(in_array('14', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>   value="14" name="funcionalidades[]" id="funcionalidades" class="flat">
                          Remover
                         </td>
                        <td class=" ">
                          <input type="checkbox"  <?php if(in_array('13', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?>  value="13" name="funcionalidades[]" id="funcionalidades" class="flat">
                          Visualizar
                         </td>
                        <td class=" "></td>
                      </tr>
                      </tbody>
                      </table>
                      
                      <table class="table table-striped responsive-utilities jambo_table bulk_action">
                    <thead>
                      <tr class="headings">
                        <th>
                          <input type="checkbox" id="check-all" class="flat">
                        </th>
                        <th class="column-title" colspan="6">Usuários </th>
                      </tr>
                    </thead>

                    <tbody>
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input type="checkbox"  value="15"  <?php if(in_array('15', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades" class="flat">
                          Consultar
                         </td>
                        <td class=" ">
                          <input type="checkbox"  value="16"  <?php if(in_array('16', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades" class="flat">
                          Cadastrar
                         </td>
                        <td class=" ">
                          <input type="checkbox"  value="17"  <?php if(in_array('17', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades" class="flat">
                          Editar
                         </td>
                        <td class=" ">
                          <input type="checkbox"  value="18"  <?php if(in_array('18', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades" class="flat">
                          Remover
                         </td>
                        <td class=" ">
                          <input type="checkbox"  value="19"  <?php if(in_array('19', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades" class="flat">
                          Visualizar
                         </td>
                      </tr>
                      </tbody>
                      </table>
                      
                      <table class="table table-striped responsive-utilities jambo_table bulk_action">
                    <thead>
                      <tr class="headings">
                        <th>
                          <input type="checkbox" id="check-all" class="flat">
                        </th>
                        <th class="column-title" colspan="6">Relatórios </th>
                      </tr>
                    </thead>

                    <tbody>
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        <td class=" ">
                          <input type="checkbox"  value="21"  <?php if(in_array('21', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades" class="flat">
                          Visualizar
                         </td>
                        <td class=" "></td>
                      </tr>
                      </tbody>
                      </table>
                  
                  
                      <table class="table table-striped responsive-utilities jambo_table bulk_action">
                    <thead>
                      <tr class="headings">
                        <th>
                          <input type="checkbox" id="check-all" class="flat">
                        </th>
                        <th class="column-title" colspan="6">Perfil Acesso </th>
                      </tr>
                    </thead>

                    <tbody>
                      <tr class="even pointer">
                        <td class="a-center ">
                        </td>
                        
                        <td class=" ">
                          <input type="checkbox"  value="20"  <?php if(in_array('20', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades" class="flat">
                          Cadastrar
                         </td>
                         
                        <td class=" ">
                          <input type="checkbox"  value="20"  <?php if(in_array('20', $array_perfis[1])){ echo "checked='checked'"; }else{ echo "";} ?> name="funcionalidades[]" id="funcionalidades" class="flat">
                          Visualizar
                         </td>
                        <td class=" "></td>
                      </tr>
                      </tbody>
                      </table>
                  
                  
                </div>
              </div>
            </div>
                 
                  
                  <div class="form-group"> 
                          	<label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                        
						    <div class="control-label col-sm-1">
						      <button type="submit" class="btn btn-default">Cadastrar</button>
						    </div>
						    <div class="control-label col-sm-2">
						      <button type="reset" class="btn btn-default" onclick="location.href='<?php echo $this->url('usuario', array('action'=>'index'));?>'">Cancelar</button>
						    </div>
				  </div>
                  
                  </form>

                </div>
              </div>
            </div>

          </div>
        </div>

        </div>

        <!-- footer content -->
        <footer>
          <div class="copyright-info">
            <p class="pull-right">© 2016 Produzido por Laislla Costa Ramos
            </p>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
      <!-- /page content -->

  <script src="<?php echo $this->basePath('js/bootstrap.min.js'); ?>"></script>

  <!-- chart js -->
  <script src="<?php echo $this->basePath('js/chartjs/chart.min.js'); ?>"></script>
  <!-- bootstrap progress js -->
  <script src="<?php echo $this->basePath('js/progressbar/bootstrap-progressbar.min.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/nicescroll/jquery.nicescroll.min.js'); ?>"></script>
  <!-- icheck -->
  <script src="<?php echo $this->basePath('js/icheck/icheck.min.js'); ?>"></script>

  <script src="<?php echo $this->basePath('js/custom.js'); ?>"></script>

  <!-- pace -->
  <script src="<?php echo $this->basePath('js/pace/pace.min.js'); ?>"></script>


