       <!-- page content -->
      <div class="right_col" role="main">

        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Perfil de Acesso </h3>
            </div>
            
          </div>
          <div class="clearfix"></div>


          <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="x_panel">
                
                <div class="x_title">
                  <h2>Administrador <small></small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"></a>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>                      
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                
                <div class="x_content">


                  <!-- Smart Wizard -->
                  <p>Marque todas as funcionalidades que esse perfil terá acesso.</p> <br>
                  
  				<form method="post" action="<?php echo $this->url('perfil-acesso/add',  array('action'=>'add'));?>" role="form" class="form-horizontal form-label-left">
                   
                  <input type="hidden" name="perfil_id" id="perfil_id" value="1">
                  <table>
                  <thead></thead>
                  <tbody>
                  <?php foreach ($funcionalidades as $funcionalidade){ ?>
                  	<tr>
                  		<td>
                  			<label>
                  				<label><input value="<?php echo $funcionalidade->funcionalidade_id; ?>" type="checkbox" name="funcionalidades[]" id="funcionalidades"><?php echo $funcionalidade->funcionalidade_nome; ?></label>
                  			</label>
                  		</td>
                  	</tr>
                  	
                  <?php } ?>
                  </tbody>
                  
                  </table>
                  
                  <div class="form-group"> 
                          	<label for="usuario_senha" class="control-label col-md-3 col-sm-3 col-xs-12"> </label>
                        
						    <div class="control-label col-sm-1">
						      <button type="submit" class="btn btn-default">Cadastrar</button>
						    </div>
						    <div class="control-label col-sm-2">
						      <button type="reset" class="btn btn-default" onclick="location.href='<?php echo $this->url('usuario', array('action'=>'index'));?>'">Cancelar</button>
						    </div>
				  </div>
                  
                  </form>

                </div>
              </div>
            </div>

          </div>
        </div>

        </div>

        <!-- footer content -->
        <footer>
          <div class="copyright-info">
            <p class="pull-right">© 2016 Produzido por Laislla Costa Ramos
            </p>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

      </div>
      <!-- /page content -->

  <script src="<?php echo $this->basePath('js/bootstrap.min.js'); ?>"></script>

  <!-- chart js -->
  <script src="<?php echo $this->basePath('js/chartjs/chart.min.js'); ?>"></script>
  <!-- bootstrap progress js -->
  <script src="<?php echo $this->basePath('js/progressbar/bootstrap-progressbar.min.js'); ?>"></script>
  <script src="<?php echo $this->basePath('js/nicescroll/jquery.nicescroll.min.js'); ?>"></script>
  <!-- icheck -->
  <script src="<?php echo $this->basePath('js/icheck/icheck.min.js'); ?>"></script>

  <script src="<?php echo $this->basePath('js/custom.js'); ?>"></script>

  <!-- pace -->
  <script src="<?php echo $this->basePath('js/pace/pace.min.js'); ?>"></script>


